CREATE TABLE sensitive_words (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word VARCHAR2(200) NOT NULL UNIQUE,
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_page_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_key VARCHAR2(255) NOT NULL UNIQUE,
  page_name VARCHAR2(255),
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled NUMBER(3) NOT NULL,
  updated_at TIMESTAMP
);

MERGE INTO sensitive_settings t
USING (SELECT 1 AS id FROM dual) s
ON (t.id = s.id)
WHEN NOT MATCHED THEN
  INSERT (id, enabled, updated_at) VALUES (1, 0, SYSTIMESTAMP);
