import { defineConfig } from 'umi';

export default defineConfig({
  npmClient: 'npm',
  antd: {},
  model: {},
  initialState: {},
  access: {},
  request: {},
  layout: {},
  locale: false,
  hash: true,
  alias: {
    '@': '/src',
  },
  routes: [
    { path: '/login', component: '@/pages/auth/login', layout: false },
    { path: '/403', component: '@/pages/result/403', layout: false },
    { path: '/404', component: '@/pages/result/404', layout: false },
    { path: '/500', component: '@/pages/result/500', layout: false },
    { path: '/result/browser-incompatible', component: '@/pages/result/browser-incompatible', layout: false },
    { path: '/result/fail', component: '@/pages/result/fail', layout: false },
    { path: '/result/maintenance', component: '@/pages/result/maintenance', layout: false },
    { path: '/result/network-error', component: '@/pages/result/network-error', layout: false },
    { path: '/result/success', component: '@/pages/result/success', layout: false },
    { path: '/', redirect: '/dashboard' },
    { path: '/dashboard', component: '@/pages/dashboard', access: 'canViewDashboard' },
    { path: '/account/center', component: '@/pages/account/center', access: 'canAccessAccountCenter' },
    { path: '/user/index', component: '@/pages/user' },
    { path: '/announcement/cards/index', component: '@/pages/announcement/cards' },
    { path: '/announcement/table/index', component: '@/pages/announcement/table' },
    { path: '/message/send/index', component: '@/pages/message/send' },
    { path: '/notification/table/index', component: '@/pages/notification/table' },
    { path: '/console/download/index', component: '@/pages/console/download' },
    { path: '/system/log/index', component: '@/pages/system/log' },
    { path: '/system/personalize/index', component: '@/pages/system/personalize' },
    { path: '/system/security/index', component: '@/pages/system/security' },
    { path: '/system/storage/index', component: '@/pages/system/storage' },
    { path: '/system/verification/index', component: '@/pages/system/verification' },
    { path: '/example/goods/index', component: '@/pages/example/goods' },
    { path: '/example/order/index', component: '@/pages/example/order' },
    { path: '/*', component: '@/pages/dynamic' },
  ],
  proxy: {
    '/api': {
      target: 'http://localhost:8080',
      changeOrigin: true,
    },
  },
});
