CREATE TABLE IF NOT EXISTS sensitive_words (
  id BIGINT NOT NULL AUTO_INCREMENT,
  word VARCHAR(200) NOT NULL,
  enabled TINYINT NOT NULL,
  created_at DATETIME NULL DEFAULT NULL,
  updated_at DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY word (word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sensitive_page_settings (
  id BIGINT NOT NULL AUTO_INCREMENT,
  page_key VARCHAR(255) NOT NULL,
  page_name VARCHAR(255) NULL DEFAULT NULL,
  enabled TINYINT NOT NULL,
  created_at DATETIME NULL DEFAULT NULL,
  updated_at DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY page_key (page_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sensitive_settings (
  id BIGINT NOT NULL AUTO_INCREMENT,
  enabled TINYINT NOT NULL,
  updated_at DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO sensitive_settings (id, enabled) VALUES (1, 0)
  ON DUPLICATE KEY UPDATE id = id;
