CREATE TABLE verification_sms_settings (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sms_enabled NUMBER(3),
  sms_provider VARCHAR2(32),
  sms_aliyun_enabled NUMBER(3),
  sms_aliyun_access_key_id VARCHAR2(256),
  sms_aliyun_access_key_secret VARCHAR2(256),
  sms_aliyun_sign_name VARCHAR2(128),
  sms_aliyun_template_code VARCHAR2(64),
  sms_aliyun_region_id VARCHAR2(64),
  sms_aliyun_endpoint VARCHAR2(255),
  sms_tencent_enabled NUMBER(3),
  sms_tencent_secret_id VARCHAR2(256),
  sms_tencent_secret_key VARCHAR2(256),
  sms_tencent_sign_name VARCHAR2(128),
  sms_tencent_template_id VARCHAR2(64),
  sms_tencent_region VARCHAR2(64),
  sms_tencent_endpoint VARCHAR2(255),
  sms_sdk_app_id VARCHAR2(64)
);

INSERT INTO verification_sms_settings (id)
SELECT 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM verification_sms_settings WHERE id = 1);
