CREATE TABLE IF NOT EXISTS verification_sms_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sms_enabled SMALLINT,
  sms_provider VARCHAR(32),
  sms_aliyun_enabled SMALLINT,
  sms_aliyun_access_key_id VARCHAR(256),
  sms_aliyun_access_key_secret VARCHAR(256),
  sms_aliyun_sign_name VARCHAR(128),
  sms_aliyun_template_code VARCHAR(64),
  sms_aliyun_region_id VARCHAR(64),
  sms_aliyun_endpoint VARCHAR(255),
  sms_tencent_enabled SMALLINT,
  sms_tencent_secret_id VARCHAR(256),
  sms_tencent_secret_key VARCHAR(256),
  sms_tencent_sign_name VARCHAR(128),
  sms_tencent_template_id VARCHAR(64),
  sms_tencent_region VARCHAR(64),
  sms_tencent_endpoint VARCHAR(255),
  sms_sdk_app_id VARCHAR(64)
);

INSERT INTO verification_sms_settings (id) VALUES (1)
  ON CONFLICT DO NOTHING;
