-- Oracle initialization script for TDesign
-- Use (SQL*Plus): @database/tdesign_init_oracle.sql
-- Note: run on an empty schema or drop existing tables first.

CREATE TABLE users (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account VARCHAR2(64) NOT NULL UNIQUE,
  guid VARCHAR2(36) NOT NULL UNIQUE,
  name VARCHAR2(64) NOT NULL,
  password_hash VARCHAR2(100) NOT NULL,
  mobile VARCHAR2(20),
  phone VARCHAR2(20),
  email VARCHAR2(100),
  id_card VARCHAR2(32),
  seat VARCHAR2(50),
  entity VARCHAR2(100),
  leader VARCHAR2(64),
  position VARCHAR2(64),
  join_day DATE,
  team VARCHAR2(255),
  status NUMBER(3) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE org_units (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id NUMBER(19),
  name VARCHAR2(128) NOT NULL,
  short_name VARCHAR2(64),
  type VARCHAR2(32) NOT NULL,
  sort_order NUMBER(10) DEFAULT 0 NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  phone VARCHAR2(32),
  email VARCHAR2(128),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE org_unit_leaders (
  org_unit_id NUMBER(19) NOT NULL,
  user_id NUMBER(19) NOT NULL,
  PRIMARY KEY (org_unit_id, user_id)
);

CREATE TABLE user_org_units (
  user_id NUMBER(19) NOT NULL,
  org_unit_id NUMBER(19) NOT NULL,
  PRIMARY KEY (user_id, org_unit_id)
);

CREATE TABLE roles (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL UNIQUE,
  description VARCHAR2(255)
);

CREATE TABLE user_roles (
  user_id NUMBER(19) NOT NULL,
  role VARCHAR2(64) NOT NULL,
  PRIMARY KEY (user_id, role)
);

CREATE TABLE role_permissions (
  role_id NUMBER(19) NOT NULL,
  permission VARCHAR2(128) NOT NULL,
  PRIMARY KEY (role_id, permission)
);

CREATE TABLE sys_menu_items (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id NUMBER(19),
  node_type VARCHAR2(16) NOT NULL,
  path VARCHAR2(255) NOT NULL,
  route_name VARCHAR2(128) NOT NULL,
  component VARCHAR2(255),
  redirect VARCHAR2(255),
  title_zh_cn VARCHAR2(64) NOT NULL,
  title_en_us VARCHAR2(64),
  icon VARCHAR2(64),
  hidden NUMBER(3) DEFAULT 0 NOT NULL,
  frame_src VARCHAR2(512),
  frame_blank NUMBER(3) DEFAULT 0 NOT NULL,
  enabled NUMBER(3) DEFAULT 1 NOT NULL,
  order_no NUMBER(10) DEFAULT 0 NOT NULL,
  actions VARCHAR2(128),
  version NUMBER(10) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_menu_items_route_name UNIQUE (route_name)
);

CREATE TABLE sys_dict (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL,
  code VARCHAR2(64) NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  remark VARCHAR2(255),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_dict_code UNIQUE (code)
);

CREATE TABLE sys_dict_items (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_id NUMBER(19) NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_dict_item_value UNIQUE (dict_id, value)
);

CREATE TABLE role_menus (
  role_id NUMBER(19) NOT NULL,
  menu_id NUMBER(19) NOT NULL,
  PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE ui_brand_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_name VARCHAR2(100),
  app_version VARCHAR2(50),
  logo_expanded_url VARCHAR2(255),
  logo_collapsed_url VARCHAR2(255),
  favicon_url VARCHAR2(255),
  qr_code_url VARCHAR2(255)
);

CREATE TABLE ui_layout_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  default_home VARCHAR2(255),
  show_footer NUMBER(3),
  is_sidebar_compact NUMBER(3),
  show_breadcrumb NUMBER(3),
  menu_auto_collapsed NUMBER(3),
  layout VARCHAR2(20),
  split_menu NUMBER(3),
  side_mode VARCHAR2(20),
  is_footer_aside NUMBER(3),
  is_sidebar_fixed NUMBER(3),
  is_header_fixed NUMBER(3),
  is_use_tabs_router NUMBER(3),
  show_header NUMBER(3)
);

CREATE TABLE ui_theme_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auto_theme NUMBER(3),
  light_start_time VARCHAR2(10),
  dark_start_time VARCHAR2(10),
  mode VARCHAR2(20),
  brand_theme VARCHAR2(20)
);

CREATE TABLE ui_footer_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  footer_company VARCHAR2(100),
  footer_icp VARCHAR2(100),
  copyright_start_year VARCHAR2(10)
);

CREATE TABLE ui_login_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_bg_url VARCHAR2(255),
  allow_multi_device_login NUMBER(3)
);

CREATE TABLE ui_legal_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_agreement CLOB,
  privacy_agreement CLOB
);

CREATE TABLE ui_system_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_retention_days NUMBER(10),
  ai_assistant_enabled NUMBER(3)
);

CREATE TABLE verification_sms_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sms_enabled NUMBER(3),
  sms_provider VARCHAR2(32),
  sms_aliyun_enabled NUMBER(3),
  sms_aliyun_access_key_id VARCHAR2(256),
  sms_aliyun_access_key_secret VARCHAR2(256),
  sms_aliyun_sign_name VARCHAR2(128),
  sms_aliyun_template_code VARCHAR2(64),
  sms_aliyun_region_id VARCHAR2(64),
  sms_aliyun_endpoint VARCHAR2(255),
  sms_tencent_enabled NUMBER(3),
  sms_tencent_secret_id VARCHAR2(256),
  sms_tencent_secret_key VARCHAR2(256),
  sms_tencent_sign_name VARCHAR2(128),
  sms_tencent_template_id VARCHAR2(64),
  sms_tencent_region VARCHAR2(64),
  sms_tencent_endpoint VARCHAR2(255),
  sms_sdk_app_id VARCHAR2(64)
);

CREATE TABLE verification_email_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_enabled NUMBER(3),
  email_host VARCHAR2(255),
  email_port NUMBER(10),
  email_username VARCHAR2(128),
  email_password VARCHAR2(256),
  email_from VARCHAR2(128),
  email_ssl NUMBER(3)
);

CREATE TABLE security_token_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_timeout_minutes NUMBER(10),
  token_timeout_minutes NUMBER(10),
  token_refresh_grace_minutes NUMBER(10)
);

CREATE TABLE security_captcha_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captcha_enabled NUMBER(3),
  captcha_type VARCHAR2(20),
  drag_captcha_width NUMBER(10),
  drag_captcha_height NUMBER(10),
  drag_captcha_threshold NUMBER(10),
  image_captcha_length NUMBER(10),
  image_captcha_noise_lines NUMBER(10)
);

CREATE TABLE security_password_policy (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password_min_length NUMBER(10),
  password_require_uppercase NUMBER(3),
  password_require_lowercase NUMBER(3),
  password_require_special NUMBER(3),
  password_allow_sequential NUMBER(3)
);

CREATE TABLE operation_logs (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR2(32) NOT NULL,
  module VARCHAR2(64),
  detail VARCHAR2(512),
  user_id NUMBER(19),
  user_guid VARCHAR2(36),
  account VARCHAR2(64),
  ip_address VARCHAR2(64),
  device_model VARCHAR2(128),
  os VARCHAR2(64),
  browser VARCHAR2(64),
  created_at TIMESTAMP
);

CREATE TABLE user_parameters (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER(19) NOT NULL,
  param_key VARCHAR2(100) NOT NULL,
  param_value CLOB NOT NULL,
  description VARCHAR2(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE storage_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR2(20) NOT NULL,
  bucket VARCHAR2(128),
  region VARCHAR2(128),
  endpoint VARCHAR2(255),
  access_key VARCHAR2(128),
  secret_key VARCHAR2(128),
  custom_domain VARCHAR2(255),
  path_prefix VARCHAR2(128),
  public_read NUMBER(3)
);

CREATE TABLE announcements (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  summary VARCHAR2(200),
  content CLOB NOT NULL,
  type VARCHAR2(32) NOT NULL,
  priority VARCHAR2(16) NOT NULL,
  status VARCHAR2(16) NOT NULL,
  cover_url VARCHAR2(255),
  attachment_url VARCHAR2(255),
  attachment_name VARCHAR2(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id NUMBER(19),
  created_by_name VARCHAR2(64),
  is_broadcasted NUMBER(3) DEFAULT 0 NOT NULL
);

CREATE TABLE notifications (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  summary VARCHAR2(200),
  content CLOB NOT NULL,
  priority VARCHAR2(16) NOT NULL,
  status VARCHAR2(16) NOT NULL,
  type VARCHAR2(32),
  cover_url VARCHAR2(512),
  attachment_url VARCHAR2(512),
  attachment_name VARCHAR2(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id NUMBER(19),
  created_by_name VARCHAR2(64)
);

CREATE TABLE ai_provider_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL,
  vendor VARCHAR2(32) NOT NULL,
  base_url VARCHAR2(255) NOT NULL,
  endpoint_path VARCHAR2(255),
  model VARCHAR2(128),
  api_key VARCHAR2(512),
  api_version VARCHAR2(64),
  temperature NUMBER,
  max_tokens NUMBER(10),
  is_default NUMBER(3),
  enabled NUMBER(3),
  extra_headers VARCHAR2(2000),
  remark VARCHAR2(512),
  last_test_status VARCHAR2(32),
  last_test_message VARCHAR2(512),
  last_tested_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_words (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word VARCHAR2(200) NOT NULL UNIQUE,
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_page_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_key VARCHAR2(255) NOT NULL UNIQUE,
  page_name VARCHAR2(255),
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled NUMBER(3) NOT NULL,
  updated_at TIMESTAMP
);

-- ----------------------------
-- Records of sys_dict
-- ----------------------------
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2001, '性别', 'gender', 1, 1, '性别选项', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2002, '地址-省', 'address_province', 1, 2, '地址省份', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2003, '地址-市', 'address_city', 1, 3, '地址城市', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2004, '地址-区', 'address_district', 1, 4, '地址区县', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2005, '公告-类型', 'announcement_type', 1, 5, '公告类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2006, '公告-优先级', 'announcement_priority', 1, 6, '公告优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2007, '公告-状态', 'announcement_status', 1, 7, '公告状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2008, '通知-类型', 'notification_type', 1, 8, '通知类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2009, '通知-优先级', 'notification_priority', 1, 9, '通知优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2010, '通知-状态', 'notification_status', 1, 10, '通知状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2011, '消息-优先级', 'message_quality', 1, 11, '消息优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2012, '日志-操作类型', 'log_action', 1, 12, '操作日志类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2013, '用户-状态', 'user_status', 1, 13, '用户状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2014, '机构-类型', 'org_type', 1, 14, '机构类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2015, '机构-状态', 'org_status', 1, 15, '机构状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2016, '菜单-节点类型', 'menu_node_type', 1, 16, '菜单节点类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2017, '菜单-权限动作', 'menu_action', 1, 17, '菜单权限动作', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2018, '存储-提供商', 'storage_provider', 1, 18, '存储提供商', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2019, '短信-通道', 'sms_provider', 1, 19, '短信通道', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2020, 'AI-厂商', 'ai_vendor', 1, 20, 'AI厂商', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

-- ----------------------------
-- Records of sys_dict_items
-- ----------------------------
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2101, 2001, '男', 'male', 'string', 1, 1, 'success', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2102, 2001, '女', 'female', 'string', 1, 2, 'danger', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2103, 2001, '未知', 'unknown', 'string', 1, 3, 'warning', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2201, 2002, '广东省', '广东省', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2202, 2002, '上海市', '上海市', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2203, 2002, '北京市', '北京市', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2204, 2002, '浙江省', '浙江省', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2301, 2003, '深圳市', '深圳市', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2302, 2003, '广州市', '广州市', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2303, 2003, '上海市', '上海市', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2304, 2003, '北京市', '北京市', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2305, 2003, '杭州市', '杭州市', 'string', 1, 5, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2401, 2004, '南山区', '南山区', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2402, 2004, '福田区', '福田区', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2403, 2004, '宝安区', '宝安区', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2404, 2004, '龙岗区', '龙岗区', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2405, 2004, '龙华区', '龙华区', 'string', 1, 5, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2406, 2004, '天河区', '天河区', 'string', 1, 6, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2407, 2004, '越秀区', '越秀区', 'string', 1, 7, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2408, 2004, '番禺区', '番禺区', 'string', 1, 8, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2409, 2004, '海珠区', '海珠区', 'string', 1, 9, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2410, 2004, '白云区', '白云区', 'string', 1, 10, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2411, 2004, '黄浦区', '黄浦区', 'string', 1, 11, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2412, 2004, '徐汇区', '徐汇区', 'string', 1, 12, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2413, 2004, '长宁区', '长宁区', 'string', 1, 13, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2414, 2004, '静安区', '静安区', 'string', 1, 14, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2415, 2004, '浦东新区', '浦东新区', 'string', 1, 15, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2416, 2004, '东城区', '东城区', 'string', 1, 16, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2417, 2004, '西城区', '西城区', 'string', 1, 17, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2418, 2004, '朝阳区', '朝阳区', 'string', 1, 18, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2419, 2004, '海淀区', '海淀区', 'string', 1, 19, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2420, 2004, '西湖区', '西湖区', 'string', 1, 20, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2421, 2004, '上城区', '上城区', 'string', 1, 21, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2422, 2004, '下城区', '下城区', 'string', 1, 22, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2423, 2004, '江干区', '江干区', 'string', 1, 23, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2501, 2005, '公告', 'announcement', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2511, 2006, '高', 'high', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2512, 2006, '中', 'middle', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2513, 2006, '低', 'low', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2521, 2007, '草稿', 'draft', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2522, 2007, '已发布', 'published', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2523, 2007, '已撤回', 'withdrawn', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2601, 2008, '通知', 'notification', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2611, 2009, '高', 'high', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2612, 2009, '中', 'middle', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2613, 2009, '低', 'low', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2621, 2010, '草稿', 'draft', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2622, 2010, '已发布', 'published', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2623, 2010, '已撤回', 'withdrawn', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2701, 2011, '高', 'high', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2702, 2011, '中', 'middle', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2703, 2011, '低', 'low', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2801, 2012, '登录', 'LOGIN', 'string', 1, 1, 'primary', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2802, 2012, '新增', 'CREATE', 'string', 1, 2, 'success', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2803, 2012, '修改', 'UPDATE', 'string', 1, 3, 'warning', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2804, 2012, '删除', 'DELETE', 'string', 1, 4, 'danger', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2901, 2013, '正常', '1', 'number', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2902, 2013, '停用', '0', 'number', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3001, 2014, '单位', 'UNIT', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3002, 2014, '部门', 'DEPARTMENT', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3003, 2014, '科室', 'SECTION', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3004, 2014, '班组', 'TEAM', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3005, 2014, '用户', 'USER', 'string', 1, 5, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3011, 2015, '正常', '1', 'number', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3012, 2015, '停用', '0', 'number', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3101, 2016, '目录', 'DIR', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3102, 2016, '页面', 'PAGE', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3103, 2016, '按钮', 'BTN', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3201, 2017, '查询', 'query', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3202, 2017, '新增', 'create', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3203, 2017, '修改', 'update', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3204, 2017, '删除', 'delete', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3301, 2018, '本地存储', 'LOCAL', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3302, 2018, '阿里云 OSS', 'ALIYUN', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3303, 2018, '腾讯云 COS', 'TENCENT', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3401, 2019, '阿里云短信服务', 'aliyun', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3402, 2019, '腾讯云短信服务', 'tencent', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3501, 2020, 'OpenAI / 兼容', 'OPENAI', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3502, 2020, 'Azure OpenAI', 'AZURE_OPENAI', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3503, 2020, 'DeepSeek', 'DEEPSEEK', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3504, 2020, '月之暗面 / Moonshot', 'MOONSHOT', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3505, 2020, '通义千问 (兼容模式)', 'QWEN', 'string', 1, 5, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict_items (id, dict_id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3506, 2020, 'Ollama 本地部署', 'OLLAMA', 'string', 1, 6, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
