-- Oracle initialization script for TDesign
-- Use (SQL*Plus): @database/tdesign_init_oracle.sql
-- Note: run on an empty schema or drop existing tables first.

CREATE TABLE users (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account VARCHAR2(64) NOT NULL UNIQUE,
  guid VARCHAR2(36) NOT NULL UNIQUE,
  name VARCHAR2(64) NOT NULL,
  password_hash VARCHAR2(100) NOT NULL,
  mobile VARCHAR2(20),
  phone VARCHAR2(20),
  email VARCHAR2(100),
  id_card VARCHAR2(32),
  seat VARCHAR2(50),
  entity VARCHAR2(100),
  leader VARCHAR2(64),
  position VARCHAR2(64),
  join_day DATE,
  team VARCHAR2(255),
  status NUMBER(3) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE org_units (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id NUMBER(19),
  name VARCHAR2(128) NOT NULL,
  short_name VARCHAR2(64),
  type VARCHAR2(32) NOT NULL,
  sort_order NUMBER(10) DEFAULT 0 NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  phone VARCHAR2(32),
  email VARCHAR2(128),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE org_unit_leaders (
  org_unit_id NUMBER(19) NOT NULL,
  user_id NUMBER(19) NOT NULL,
  PRIMARY KEY (org_unit_id, user_id)
);

CREATE TABLE user_org_units (
  user_id NUMBER(19) NOT NULL,
  org_unit_id NUMBER(19) NOT NULL,
  PRIMARY KEY (user_id, org_unit_id)
);

CREATE TABLE roles (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL UNIQUE,
  description VARCHAR2(255)
);

CREATE TABLE user_roles (
  user_id NUMBER(19) NOT NULL,
  role VARCHAR2(64) NOT NULL,
  PRIMARY KEY (user_id, role)
);

CREATE TABLE role_permissions (
  role_id NUMBER(19) NOT NULL,
  permission VARCHAR2(128) NOT NULL,
  PRIMARY KEY (role_id, permission)
);

CREATE TABLE sys_menu_items (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id NUMBER(19),
  node_type VARCHAR2(16) NOT NULL,
  path VARCHAR2(255) NOT NULL,
  route_name VARCHAR2(128) NOT NULL,
  component VARCHAR2(255),
  redirect VARCHAR2(255),
  title_zh_cn VARCHAR2(64) NOT NULL,
  title_en_us VARCHAR2(64),
  icon VARCHAR2(64),
  hidden NUMBER(3) DEFAULT 0 NOT NULL,
  frame_src VARCHAR2(512),
  frame_blank NUMBER(3) DEFAULT 0 NOT NULL,
  enabled NUMBER(3) DEFAULT 1 NOT NULL,
  order_no NUMBER(10) DEFAULT 0 NOT NULL,
  actions VARCHAR2(128),
  version NUMBER(10) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_menu_items_route_name UNIQUE (route_name)
);

CREATE TABLE sys_dict (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL,
  code VARCHAR2(64) NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  remark VARCHAR2(255),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_dict_code UNIQUE (code)
);

CREATE TABLE sys_dict_items (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_id NUMBER(19) NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_dict_item_value UNIQUE (dict_id, value)
);

CREATE TABLE role_menus (
  role_id NUMBER(19) NOT NULL,
  menu_id NUMBER(19) NOT NULL,
  PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE ui_brand_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_name VARCHAR2(100),
  app_version VARCHAR2(50),
  logo_expanded_url VARCHAR2(255),
  logo_collapsed_url VARCHAR2(255),
  favicon_url VARCHAR2(255),
  qr_code_url VARCHAR2(255)
);

CREATE TABLE ui_layout_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  default_home VARCHAR2(255),
  show_footer NUMBER(3),
  is_sidebar_compact NUMBER(3),
  show_breadcrumb NUMBER(3),
  menu_auto_collapsed NUMBER(3),
  layout VARCHAR2(20),
  split_menu NUMBER(3),
  side_mode VARCHAR2(20),
  is_footer_aside NUMBER(3),
  is_sidebar_fixed NUMBER(3),
  is_header_fixed NUMBER(3),
  is_use_tabs_router NUMBER(3),
  show_header NUMBER(3)
);

CREATE TABLE ui_theme_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auto_theme NUMBER(3),
  light_start_time VARCHAR2(10),
  dark_start_time VARCHAR2(10),
  mode VARCHAR2(20),
  brand_theme VARCHAR2(20)
);

CREATE TABLE ui_footer_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  footer_company VARCHAR2(100),
  footer_icp VARCHAR2(100),
  copyright_start_year VARCHAR2(10)
);

CREATE TABLE ui_login_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_bg_url VARCHAR2(255),
  allow_multi_device_login NUMBER(3)
);

CREATE TABLE ui_legal_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_agreement CLOB,
  privacy_agreement CLOB
);

CREATE TABLE ui_system_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_retention_days NUMBER(10),
  ai_assistant_enabled NUMBER(3)
);

CREATE TABLE verification_sms_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sms_enabled NUMBER(3),
  sms_provider VARCHAR2(32),
  sms_aliyun_enabled NUMBER(3),
  sms_aliyun_access_key_id VARCHAR2(256),
  sms_aliyun_access_key_secret VARCHAR2(256),
  sms_aliyun_sign_name VARCHAR2(128),
  sms_aliyun_template_code VARCHAR2(64),
  sms_aliyun_region_id VARCHAR2(64),
  sms_aliyun_endpoint VARCHAR2(255),
  sms_tencent_enabled NUMBER(3),
  sms_tencent_secret_id VARCHAR2(256),
  sms_tencent_secret_key VARCHAR2(256),
  sms_tencent_sign_name VARCHAR2(128),
  sms_tencent_template_id VARCHAR2(64),
  sms_tencent_region VARCHAR2(64),
  sms_tencent_endpoint VARCHAR2(255),
  sms_sdk_app_id VARCHAR2(64)
);

CREATE TABLE verification_email_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_enabled NUMBER(3),
  email_host VARCHAR2(255),
  email_port NUMBER(10),
  email_username VARCHAR2(128),
  email_password VARCHAR2(256),
  email_from VARCHAR2(128),
  email_ssl NUMBER(3)
);

CREATE TABLE security_token_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_timeout_minutes NUMBER(10),
  token_timeout_minutes NUMBER(10),
  token_refresh_grace_minutes NUMBER(10)
);

CREATE TABLE security_captcha_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captcha_enabled NUMBER(3),
  captcha_type VARCHAR2(20),
  drag_captcha_width NUMBER(10),
  drag_captcha_height NUMBER(10),
  drag_captcha_threshold NUMBER(10),
  image_captcha_length NUMBER(10),
  image_captcha_noise_lines NUMBER(10)
);

CREATE TABLE security_password_policy (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password_min_length NUMBER(10),
  password_require_uppercase NUMBER(3),
  password_require_lowercase NUMBER(3),
  password_require_special NUMBER(3),
  password_allow_sequential NUMBER(3)
);

CREATE TABLE operation_logs (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR2(32) NOT NULL,
  module VARCHAR2(64),
  detail VARCHAR2(512),
  user_id NUMBER(19),
  user_guid VARCHAR2(36),
  account VARCHAR2(64),
  ip_address VARCHAR2(64),
  device_model VARCHAR2(128),
  os VARCHAR2(64),
  browser VARCHAR2(64),
  created_at TIMESTAMP
);

CREATE TABLE user_parameters (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER(19) NOT NULL,
  param_key VARCHAR2(100) NOT NULL,
  param_value CLOB NOT NULL,
  description VARCHAR2(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE storage_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR2(20) NOT NULL,
  bucket VARCHAR2(128),
  region VARCHAR2(128),
  endpoint VARCHAR2(255),
  access_key VARCHAR2(128),
  secret_key VARCHAR2(128),
  custom_domain VARCHAR2(255),
  path_prefix VARCHAR2(128),
  public_read NUMBER(3)
);

CREATE TABLE announcements (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  summary VARCHAR2(200),
  content CLOB NOT NULL,
  type VARCHAR2(32) NOT NULL,
  priority VARCHAR2(16) NOT NULL,
  status VARCHAR2(16) NOT NULL,
  cover_url VARCHAR2(255),
  attachment_url VARCHAR2(255),
  attachment_name VARCHAR2(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id NUMBER(19),
  created_by_name VARCHAR2(64),
  is_broadcasted NUMBER(3) DEFAULT 0 NOT NULL
);

CREATE TABLE notifications (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  summary VARCHAR2(200),
  content CLOB NOT NULL,
  priority VARCHAR2(16) NOT NULL,
  status VARCHAR2(16) NOT NULL,
  type VARCHAR2(32),
  cover_url VARCHAR2(512),
  attachment_url VARCHAR2(512),
  attachment_name VARCHAR2(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id NUMBER(19),
  created_by_name VARCHAR2(64)
);

CREATE TABLE ai_provider_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL,
  vendor VARCHAR2(32) NOT NULL,
  base_url VARCHAR2(255) NOT NULL,
  endpoint_path VARCHAR2(255),
  model VARCHAR2(128),
  api_key VARCHAR2(512),
  api_version VARCHAR2(64),
  temperature NUMBER,
  max_tokens NUMBER(10),
  is_default NUMBER(3),
  enabled NUMBER(3),
  extra_headers VARCHAR2(2000),
  remark VARCHAR2(512),
  last_test_status VARCHAR2(32),
  last_test_message VARCHAR2(512),
  last_tested_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_words (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word VARCHAR2(200) NOT NULL UNIQUE,
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_page_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_key VARCHAR2(255) NOT NULL UNIQUE,
  page_name VARCHAR2(255),
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled NUMBER(3) NOT NULL,
  updated_at TIMESTAMP
);
