-- PostgreSQL initialization script for TDesign
-- Use: psql -d tdesign -f database/tdesign_init_pg.sql

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account VARCHAR(64) NOT NULL UNIQUE,
  guid VARCHAR(36) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  mobile VARCHAR(20),
  phone VARCHAR(20),
  email VARCHAR(100),
  id_card VARCHAR(32),
  seat VARCHAR(50),
  entity VARCHAR(100),
  leader VARCHAR(64),
  position VARCHAR(64),
  join_day DATE,
  team VARCHAR(255),
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS org_units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT,
  name VARCHAR(128) NOT NULL,
  short_name VARCHAR(64),
  type VARCHAR(32) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  phone VARCHAR(32),
  email VARCHAR(128),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS org_unit_leaders (
  org_unit_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  PRIMARY KEY (org_unit_id, user_id)
);

CREATE TABLE IF NOT EXISTS user_org_units (
  user_id BIGINT NOT NULL,
  org_unit_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, org_unit_id)
);

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(64) UNIQUE NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT NOT NULL,
  role VARCHAR(64) NOT NULL,
  PRIMARY KEY (user_id, role)
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id BIGINT NOT NULL,
  permission VARCHAR(128) NOT NULL,
  PRIMARY KEY (role_id, permission)
);

CREATE TABLE IF NOT EXISTS sys_menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT,
  node_type VARCHAR(16) NOT NULL,
  path VARCHAR(255) NOT NULL,
  route_name VARCHAR(128) NOT NULL,
  component VARCHAR(255),
  redirect VARCHAR(255),
  title_zh_cn VARCHAR(64) NOT NULL,
  title_en_us VARCHAR(64),
  icon VARCHAR(64),
  hidden SMALLINT NOT NULL DEFAULT 0,
  frame_src VARCHAR(512),
  frame_blank SMALLINT NOT NULL DEFAULT 0,
  enabled SMALLINT NOT NULL DEFAULT 1,
  order_no INTEGER NOT NULL DEFAULT 0,
  actions VARCHAR(128),
  version INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_sys_menu_items_route_name UNIQUE (route_name)
);

CREATE TABLE IF NOT EXISTS sys_dict (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  status SMALLINT NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0,
  remark VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_dict_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_id BIGINT NOT NULL,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_sys_dict_item_value UNIQUE (dict_id, value)
);

CREATE TABLE IF NOT EXISTS role_menus (
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE IF NOT EXISTS ui_brand_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_name VARCHAR(100),
  app_version VARCHAR(50),
  logo_expanded_url VARCHAR(255),
  logo_collapsed_url VARCHAR(255),
  favicon_url VARCHAR(255),
  qr_code_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ui_layout_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  default_home VARCHAR(255),
  show_footer SMALLINT,
  is_sidebar_compact SMALLINT,
  show_breadcrumb SMALLINT,
  menu_auto_collapsed SMALLINT,
  layout VARCHAR(20),
  split_menu SMALLINT,
  side_mode VARCHAR(20),
  is_footer_aside SMALLINT,
  is_sidebar_fixed SMALLINT,
  is_header_fixed SMALLINT,
  is_use_tabs_router SMALLINT,
  show_header SMALLINT
);

CREATE TABLE IF NOT EXISTS ui_theme_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auto_theme SMALLINT,
  light_start_time VARCHAR(10),
  dark_start_time VARCHAR(10),
  mode VARCHAR(20),
  brand_theme VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS ui_footer_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  footer_company VARCHAR(100),
  footer_icp VARCHAR(100),
  copyright_start_year VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS ui_login_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_bg_url VARCHAR(255),
  allow_multi_device_login SMALLINT
);

CREATE TABLE IF NOT EXISTS ui_legal_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_agreement TEXT,
  privacy_agreement TEXT
);

CREATE TABLE IF NOT EXISTS ui_system_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_retention_days INTEGER,
  ai_assistant_enabled SMALLINT
);

CREATE TABLE IF NOT EXISTS verification_sms_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sms_enabled SMALLINT,
  sms_provider VARCHAR(32),
  sms_aliyun_enabled SMALLINT,
  sms_aliyun_access_key_id VARCHAR(256),
  sms_aliyun_access_key_secret VARCHAR(256),
  sms_aliyun_sign_name VARCHAR(128),
  sms_aliyun_template_code VARCHAR(64),
  sms_aliyun_region_id VARCHAR(64),
  sms_aliyun_endpoint VARCHAR(255),
  sms_tencent_enabled SMALLINT,
  sms_tencent_secret_id VARCHAR(256),
  sms_tencent_secret_key VARCHAR(256),
  sms_tencent_sign_name VARCHAR(128),
  sms_tencent_template_id VARCHAR(64),
  sms_tencent_region VARCHAR(64),
  sms_tencent_endpoint VARCHAR(255),
  sms_sdk_app_id VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS verification_email_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_enabled SMALLINT,
  email_host VARCHAR(255),
  email_port INTEGER,
  email_username VARCHAR(128),
  email_password VARCHAR(256),
  email_from VARCHAR(128),
  email_ssl SMALLINT
);

CREATE TABLE IF NOT EXISTS security_token_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_timeout_minutes INTEGER,
  token_timeout_minutes INTEGER,
  token_refresh_grace_minutes INTEGER
);

CREATE TABLE IF NOT EXISTS security_captcha_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captcha_enabled SMALLINT,
  captcha_type VARCHAR(20),
  drag_captcha_width INTEGER,
  drag_captcha_height INTEGER,
  drag_captcha_threshold INTEGER,
  image_captcha_length INTEGER,
  image_captcha_noise_lines INTEGER
);

CREATE TABLE IF NOT EXISTS security_password_policy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password_min_length INTEGER,
  password_require_uppercase SMALLINT,
  password_require_lowercase SMALLINT,
  password_require_special SMALLINT,
  password_allow_sequential SMALLINT
);

CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(32) NOT NULL,
  module VARCHAR(64),
  detail VARCHAR(512),
  user_id BIGINT,
  user_guid VARCHAR(36),
  account VARCHAR(64),
  ip_address VARCHAR(64),
  device_model VARCHAR(128),
  os VARCHAR(64),
  browser VARCHAR(64),
  created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_parameters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  param_key VARCHAR(100) NOT NULL,
  param_value TEXT NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS storage_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(20) NOT NULL,
  bucket VARCHAR(128),
  region VARCHAR(128),
  endpoint VARCHAR(255),
  access_key VARCHAR(128),
  secret_key VARCHAR(128),
  custom_domain VARCHAR(255),
  path_prefix VARCHAR(128),
  public_read SMALLINT
);

CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  summary VARCHAR(200),
  content TEXT NOT NULL,
  type VARCHAR(32) NOT NULL,
  priority VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  cover_url VARCHAR(255),
  attachment_url VARCHAR(255),
  attachment_name VARCHAR(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id BIGINT,
  created_by_name VARCHAR(64),
  is_broadcasted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  summary VARCHAR(200),
  content TEXT NOT NULL,
  priority VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  type VARCHAR(32),
  cover_url VARCHAR(512),
  attachment_url VARCHAR(512),
  attachment_name VARCHAR(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id BIGINT,
  created_by_name VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS ai_provider_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  vendor VARCHAR(32) NOT NULL,
  base_url VARCHAR(255) NOT NULL,
  endpoint_path VARCHAR(255),
  model VARCHAR(128),
  api_key VARCHAR(512),
  api_version VARCHAR(64),
  temperature DOUBLE PRECISION,
  max_tokens INTEGER,
  is_default SMALLINT,
  enabled SMALLINT,
  extra_headers VARCHAR(2000),
  remark VARCHAR(512),
  last_test_status VARCHAR(32),
  last_test_message VARCHAR(512),
  last_tested_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sensitive_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word VARCHAR(200) NOT NULL UNIQUE,
  enabled SMALLINT NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sensitive_page_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_key VARCHAR(255) NOT NULL UNIQUE,
  page_name VARCHAR(255),
  enabled SMALLINT NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sensitive_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled SMALLINT NOT NULL,
  updated_at TIMESTAMP
);

COMMIT;
