-- Table/Column comments for PostgreSQL

COMMENT ON TABLE ai_provider_settings IS '表: ai_provider_settings';
COMMENT ON COLUMN ai_provider_settings.id IS 'id';
COMMENT ON COLUMN ai_provider_settings.name IS 'name';
COMMENT ON COLUMN ai_provider_settings.vendor IS 'vendor';
COMMENT ON COLUMN ai_provider_settings.base_url IS 'base_url';
COMMENT ON COLUMN ai_provider_settings.endpoint_path IS 'endpoint_path';
COMMENT ON COLUMN ai_provider_settings.model IS 'model';
COMMENT ON COLUMN ai_provider_settings.api_key IS 'api_key';
COMMENT ON COLUMN ai_provider_settings.api_version IS 'api_version';
COMMENT ON COLUMN ai_provider_settings.temperature IS 'temperature';
COMMENT ON COLUMN ai_provider_settings.max_tokens IS 'max_tokens';
COMMENT ON COLUMN ai_provider_settings.is_default IS 'is_default';
COMMENT ON COLUMN ai_provider_settings.enabled IS 'enabled';
COMMENT ON COLUMN ai_provider_settings.extra_headers IS 'extra_headers';
COMMENT ON COLUMN ai_provider_settings.remark IS 'remark';
COMMENT ON COLUMN ai_provider_settings.last_test_status IS 'last_test_status';
COMMENT ON COLUMN ai_provider_settings.last_test_message IS 'last_test_message';
COMMENT ON COLUMN ai_provider_settings.last_tested_at IS 'last_tested_at';
COMMENT ON COLUMN ai_provider_settings.created_at IS 'created_at';
COMMENT ON COLUMN ai_provider_settings.updated_at IS 'updated_at';
COMMENT ON TABLE announcements IS '表: announcements';
COMMENT ON COLUMN announcements.id IS 'id';
COMMENT ON COLUMN announcements.title IS 'title';
COMMENT ON COLUMN announcements.summary IS 'summary';
COMMENT ON COLUMN announcements.content IS 'content';
COMMENT ON COLUMN announcements.type IS 'type';
COMMENT ON COLUMN announcements.priority IS 'priority';
COMMENT ON COLUMN announcements.status IS 'status';
COMMENT ON COLUMN announcements.cover_url IS 'cover_url';
COMMENT ON COLUMN announcements.publish_at IS 'publish_at';
COMMENT ON COLUMN announcements.created_at IS 'created_at';
COMMENT ON COLUMN announcements.updated_at IS 'updated_at';
COMMENT ON COLUMN announcements.created_by_id IS 'created_by_id';
COMMENT ON COLUMN announcements.created_by_name IS 'created_by_name';
COMMENT ON COLUMN announcements.attachment_url IS 'attachment_url';
COMMENT ON COLUMN announcements.attachment_name IS 'attachment_name';
COMMENT ON COLUMN announcements.is_broadcasted IS 'is_broadcasted';
COMMENT ON TABLE file_download_history IS '表: file_download_history';
COMMENT ON COLUMN file_download_history.id IS 'id';
COMMENT ON COLUMN file_download_history.user_id IS 'user_id';
COMMENT ON COLUMN file_download_history.file_id IS 'file_id';
COMMENT ON COLUMN file_download_history.file_name IS 'file_name';
COMMENT ON COLUMN file_download_history.size_bytes IS 'size_bytes';
COMMENT ON COLUMN file_download_history.downloaded_at IS 'downloaded_at';
COMMENT ON TABLE file_resources IS '表: file_resources';
COMMENT ON COLUMN file_resources.id IS 'id';
COMMENT ON COLUMN file_resources.content IS 'content';
COMMENT ON COLUMN file_resources.file_name IS 'file_name';
COMMENT ON COLUMN file_resources.suffix IS 'suffix';
COMMENT ON COLUMN file_resources.file_url IS 'file_url';
COMMENT ON COLUMN file_resources.created_by_id IS 'created_by_id';
COMMENT ON COLUMN file_resources.created_by_name IS 'created_by_name';
COMMENT ON COLUMN file_resources.created_at IS 'created_at';
COMMENT ON COLUMN file_resources.updated_at IS 'updated_at';
COMMENT ON TABLE messages IS '表: messages';
COMMENT ON COLUMN messages.id IS 'id';
COMMENT ON COLUMN messages.to_user_id IS 'to_user_id';
COMMENT ON COLUMN messages.content IS 'content';
COMMENT ON COLUMN messages.type IS 'type';
COMMENT ON COLUMN messages.status IS 'status';
COMMENT ON COLUMN messages.collected IS 'collected';
COMMENT ON COLUMN messages.quality IS 'quality';
COMMENT ON COLUMN messages.created_at IS 'created_at';
COMMENT ON TABLE notifications IS '表: notifications';
COMMENT ON COLUMN notifications.id IS 'id';
COMMENT ON COLUMN notifications.title IS 'title';
COMMENT ON COLUMN notifications.summary IS 'summary';
COMMENT ON COLUMN notifications.content IS 'content';
COMMENT ON COLUMN notifications.priority IS 'priority';
COMMENT ON COLUMN notifications.status IS 'status';
COMMENT ON COLUMN notifications.publish_at IS 'publish_at';
COMMENT ON COLUMN notifications.created_at IS 'created_at';
COMMENT ON COLUMN notifications.updated_at IS 'updated_at';
COMMENT ON COLUMN notifications.created_by_id IS 'created_by_id';
COMMENT ON COLUMN notifications.created_by_name IS 'created_by_name';
COMMENT ON COLUMN notifications.type IS 'type';
COMMENT ON COLUMN notifications.cover_url IS 'cover_url';
COMMENT ON COLUMN notifications.attachment_url IS 'attachment_url';
COMMENT ON COLUMN notifications.attachment_name IS 'attachment_name';
COMMENT ON TABLE operation_logs IS '表: operation_logs';
COMMENT ON COLUMN operation_logs.id IS 'id';
COMMENT ON COLUMN operation_logs.action IS 'action';
COMMENT ON COLUMN operation_logs.module IS 'module';
COMMENT ON COLUMN operation_logs.detail IS 'detail';
COMMENT ON COLUMN operation_logs.user_id IS 'user_id';
COMMENT ON COLUMN operation_logs.account IS 'account';
COMMENT ON COLUMN operation_logs.ip_address IS 'ip_address';
COMMENT ON COLUMN operation_logs.device_model IS 'device_model';
COMMENT ON COLUMN operation_logs.os IS 'os';
COMMENT ON COLUMN operation_logs.browser IS 'browser';
COMMENT ON COLUMN operation_logs.created_at IS 'created_at';
COMMENT ON COLUMN operation_logs.user_guid IS 'user_guid';
COMMENT ON TABLE role_menus IS '表: role_menus';
COMMENT ON COLUMN role_menus.role_id IS 'role_id';
COMMENT ON COLUMN role_menus.menu_id IS 'menu_id';
COMMENT ON TABLE role_permissions IS '表: role_permissions';
COMMENT ON COLUMN role_permissions.role_id IS 'role_id';
COMMENT ON COLUMN role_permissions.permission IS 'permission';
COMMENT ON TABLE roles IS '表: roles';
COMMENT ON COLUMN roles.id IS 'id';
COMMENT ON COLUMN roles.name IS 'name';
COMMENT ON COLUMN roles.description IS 'description';
COMMENT ON TABLE security_captcha_settings IS '表: security_captcha_settings';
COMMENT ON COLUMN security_captcha_settings.id IS 'id';
COMMENT ON COLUMN security_captcha_settings.captcha_type IS 'captcha_type';
COMMENT ON COLUMN security_captcha_settings.drag_captcha_width IS 'drag_captcha_width';
COMMENT ON COLUMN security_captcha_settings.drag_captcha_height IS 'drag_captcha_height';
COMMENT ON COLUMN security_captcha_settings.drag_captcha_threshold IS 'drag_captcha_threshold';
COMMENT ON COLUMN security_captcha_settings.image_captcha_length IS 'image_captcha_length';
COMMENT ON COLUMN security_captcha_settings.image_captcha_noise_lines IS 'image_captcha_noise_lines';
COMMENT ON COLUMN security_captcha_settings.captcha_enabled IS 'captcha_enabled';
COMMENT ON TABLE security_password_policy IS '表: security_password_policy';
COMMENT ON COLUMN security_password_policy.id IS 'id';
COMMENT ON COLUMN security_password_policy.password_min_length IS 'password_min_length';
COMMENT ON COLUMN security_password_policy.password_require_uppercase IS 'password_require_uppercase';
COMMENT ON COLUMN security_password_policy.password_require_lowercase IS 'password_require_lowercase';
COMMENT ON COLUMN security_password_policy.password_require_special IS 'password_require_special';
COMMENT ON COLUMN security_password_policy.password_allow_sequential IS 'password_allow_sequential';
COMMENT ON TABLE security_token_settings IS '表: security_token_settings';
COMMENT ON COLUMN security_token_settings.id IS 'id';
COMMENT ON COLUMN security_token_settings.session_timeout_minutes IS 'session_timeout_minutes';
COMMENT ON COLUMN security_token_settings.token_timeout_minutes IS 'token_timeout_minutes';
COMMENT ON COLUMN security_token_settings.token_refresh_grace_minutes IS 'token_refresh_grace_minutes';
COMMENT ON COLUMN security_token_settings.allow_url_token_param IS 'allow_url_token_param';
COMMENT ON TABLE sensitive_page_settings IS '表: sensitive_page_settings';
COMMENT ON COLUMN sensitive_page_settings.id IS 'id';
COMMENT ON COLUMN sensitive_page_settings.page_key IS 'page_key';
COMMENT ON COLUMN sensitive_page_settings.page_name IS 'page_name';
COMMENT ON COLUMN sensitive_page_settings.enabled IS 'enabled';
COMMENT ON COLUMN sensitive_page_settings.created_at IS 'created_at';
COMMENT ON COLUMN sensitive_page_settings.updated_at IS 'updated_at';
COMMENT ON TABLE sensitive_settings IS '表: sensitive_settings';
COMMENT ON COLUMN sensitive_settings.id IS 'id';
COMMENT ON COLUMN sensitive_settings.enabled IS 'enabled';
COMMENT ON COLUMN sensitive_settings.updated_at IS 'updated_at';
COMMENT ON TABLE sensitive_words IS '表: sensitive_words';
COMMENT ON COLUMN sensitive_words.id IS 'id';
COMMENT ON COLUMN sensitive_words.word IS 'word';
COMMENT ON COLUMN sensitive_words.enabled IS 'enabled';
COMMENT ON COLUMN sensitive_words.created_at IS 'created_at';
COMMENT ON COLUMN sensitive_words.updated_at IS 'updated_at';
COMMENT ON TABLE storage_settings IS '表: storage_settings';
COMMENT ON COLUMN storage_settings.id IS 'id';
COMMENT ON COLUMN storage_settings.provider IS 'provider';
COMMENT ON COLUMN storage_settings.bucket IS 'bucket';
COMMENT ON COLUMN storage_settings.region IS 'region';
COMMENT ON COLUMN storage_settings.endpoint IS 'endpoint';
COMMENT ON COLUMN storage_settings.access_key IS 'access_key';
COMMENT ON COLUMN storage_settings.secret_key IS 'secret_key';
COMMENT ON COLUMN storage_settings.custom_domain IS 'custom_domain';
COMMENT ON COLUMN storage_settings.path_prefix IS 'path_prefix';
COMMENT ON COLUMN storage_settings.public_read IS 'public_read';
COMMENT ON TABLE sys_menu_items IS '表: sys_menu_items';
COMMENT ON COLUMN sys_menu_items.id IS 'id';
COMMENT ON COLUMN sys_menu_items.parent_id IS 'parent_id';
COMMENT ON COLUMN sys_menu_items.node_type IS 'node_type';
COMMENT ON COLUMN sys_menu_items.path IS 'path';
COMMENT ON COLUMN sys_menu_items.route_name IS 'route_name';
COMMENT ON COLUMN sys_menu_items.component IS 'component';
COMMENT ON COLUMN sys_menu_items.redirect IS 'redirect';
COMMENT ON COLUMN sys_menu_items.title_zh_cn IS 'title_zh_cn';
COMMENT ON COLUMN sys_menu_items.title_en_us IS 'title_en_us';
COMMENT ON COLUMN sys_menu_items.icon IS 'icon';
COMMENT ON COLUMN sys_menu_items.hidden IS 'hidden';
COMMENT ON COLUMN sys_menu_items.keep_alive IS 'keep_alive';
COMMENT ON COLUMN sys_menu_items.frame_src IS 'frame_src';
COMMENT ON COLUMN sys_menu_items.frame_blank IS 'frame_blank';
COMMENT ON COLUMN sys_menu_items.enabled IS 'enabled';
COMMENT ON COLUMN sys_menu_items.require_role IS 'require_role';
COMMENT ON COLUMN sys_menu_items.require_permission IS 'require_permission';
COMMENT ON COLUMN sys_menu_items.order_no IS 'order_no';
COMMENT ON COLUMN sys_menu_items.version IS 'version';
COMMENT ON COLUMN sys_menu_items.created_at IS 'created_at';
COMMENT ON COLUMN sys_menu_items.updated_at IS 'updated_at';
COMMENT ON COLUMN sys_menu_items.actions IS 'actions';
COMMENT ON TABLE ui_brand_settings IS '表: ui_brand_settings';
COMMENT ON COLUMN ui_brand_settings.id IS 'id';
COMMENT ON COLUMN ui_brand_settings.website_name IS 'website_name';
COMMENT ON COLUMN ui_brand_settings.app_version IS 'app_version';
COMMENT ON COLUMN ui_brand_settings.logo_expanded_url IS 'logo_expanded_url';
COMMENT ON COLUMN ui_brand_settings.logo_collapsed_url IS 'logo_collapsed_url';
COMMENT ON COLUMN ui_brand_settings.favicon_url IS 'favicon_url';
COMMENT ON COLUMN ui_brand_settings.qr_code_url IS 'qr_code_url';
COMMENT ON TABLE ui_footer_settings IS '表: ui_footer_settings';
COMMENT ON COLUMN ui_footer_settings.id IS 'id';
COMMENT ON COLUMN ui_footer_settings.footer_company IS 'footer_company';
COMMENT ON COLUMN ui_footer_settings.footer_icp IS 'footer_icp';
COMMENT ON COLUMN ui_footer_settings.copyright_start_year IS 'copyright_start_year';
COMMENT ON TABLE ui_layout_settings IS '表: ui_layout_settings';
COMMENT ON COLUMN ui_layout_settings.id IS 'id';
COMMENT ON COLUMN ui_layout_settings.default_home IS 'default_home';
COMMENT ON COLUMN ui_layout_settings.show_footer IS 'show_footer';
COMMENT ON COLUMN ui_layout_settings.is_sidebar_compact IS 'is_sidebar_compact';
COMMENT ON COLUMN ui_layout_settings.show_breadcrumb IS 'show_breadcrumb';
COMMENT ON COLUMN ui_layout_settings.menu_auto_collapsed IS 'menu_auto_collapsed';
COMMENT ON COLUMN ui_layout_settings.layout IS 'layout';
COMMENT ON COLUMN ui_layout_settings.split_menu IS 'split_menu';
COMMENT ON COLUMN ui_layout_settings.side_mode IS 'side_mode';
COMMENT ON COLUMN ui_layout_settings.is_footer_aside IS 'is_footer_aside';
COMMENT ON COLUMN ui_layout_settings.is_sidebar_fixed IS 'is_sidebar_fixed';
COMMENT ON COLUMN ui_layout_settings.is_header_fixed IS 'is_header_fixed';
COMMENT ON COLUMN ui_layout_settings.is_use_tabs_router IS 'is_use_tabs_router';
COMMENT ON COLUMN ui_layout_settings.show_header IS 'show_header';
COMMENT ON TABLE ui_legal_settings IS '表: ui_legal_settings';
COMMENT ON COLUMN ui_legal_settings.id IS 'id';
COMMENT ON COLUMN ui_legal_settings.user_agreement IS 'user_agreement';
COMMENT ON COLUMN ui_legal_settings.privacy_agreement IS 'privacy_agreement';
COMMENT ON TABLE ui_login_settings IS '表: ui_login_settings';
COMMENT ON COLUMN ui_login_settings.id IS 'id';
COMMENT ON COLUMN ui_login_settings.login_bg_url IS 'login_bg_url';
COMMENT ON COLUMN ui_login_settings.allow_multi_device_login IS 'allow_multi_device_login';
COMMENT ON TABLE ui_system_settings IS '表: ui_system_settings';
COMMENT ON COLUMN ui_system_settings.id IS 'id';
COMMENT ON COLUMN ui_system_settings.log_retention_days IS 'log_retention_days';
COMMENT ON COLUMN ui_system_settings.ai_assistant_enabled IS 'ai_assistant_enabled';
COMMENT ON COLUMN ui_system_settings.maintenance_enabled IS 'maintenance_enabled';
COMMENT ON COLUMN ui_system_settings.maintenance_message IS 'maintenance_message';
COMMENT ON TABLE ui_theme_settings IS '表: ui_theme_settings';
COMMENT ON COLUMN ui_theme_settings.id IS 'id';
COMMENT ON COLUMN ui_theme_settings.auto_theme IS 'auto_theme';
COMMENT ON COLUMN ui_theme_settings.light_start_time IS 'light_start_time';
COMMENT ON COLUMN ui_theme_settings.dark_start_time IS 'dark_start_time';
COMMENT ON COLUMN ui_theme_settings.mode IS 'mode';
COMMENT ON COLUMN ui_theme_settings.brand_theme IS 'brand_theme';
COMMENT ON TABLE user_parameters IS '表: user_parameters';
COMMENT ON COLUMN user_parameters.id IS 'id';
COMMENT ON COLUMN user_parameters.user_id IS 'user_id';
COMMENT ON COLUMN user_parameters.param_key IS 'param_key';
COMMENT ON COLUMN user_parameters.param_value IS 'param_value';
COMMENT ON COLUMN user_parameters.description IS 'description';
COMMENT ON COLUMN user_parameters.created_at IS 'created_at';
COMMENT ON COLUMN user_parameters.updated_at IS 'updated_at';
COMMENT ON TABLE user_roles IS '表: user_roles';
COMMENT ON COLUMN user_roles.user_id IS 'user_id';
COMMENT ON COLUMN user_roles.role IS 'role';
COMMENT ON TABLE users IS '表: users';
COMMENT ON COLUMN users.id IS 'id';
COMMENT ON COLUMN users.account IS 'account';
COMMENT ON COLUMN users.name IS 'name';
COMMENT ON COLUMN users.password_hash IS 'password_hash';
COMMENT ON COLUMN users.mobile IS 'mobile';
COMMENT ON COLUMN users.phone IS 'phone';
COMMENT ON COLUMN users.email IS 'email';
COMMENT ON COLUMN users.seat IS 'seat';
COMMENT ON COLUMN users.entity IS 'entity';
COMMENT ON COLUMN users.leader IS 'leader';
COMMENT ON COLUMN users.position IS 'position';
COMMENT ON COLUMN users.join_day IS 'join_day';
COMMENT ON COLUMN users.team IS 'team';
COMMENT ON COLUMN users.gender IS 'gender';
COMMENT ON COLUMN users.nickname IS 'nickname';
COMMENT ON COLUMN users.province IS 'province';
COMMENT ON COLUMN users.city IS 'city';
COMMENT ON COLUMN users.district IS 'district';
COMMENT ON COLUMN users.address IS 'address';
COMMENT ON COLUMN users.introduction IS 'introduction';
COMMENT ON COLUMN users.avatar IS 'avatar';
COMMENT ON COLUMN users.tags IS 'tags';
COMMENT ON COLUMN users.id_card IS 'id_card';
COMMENT ON COLUMN users.guid IS 'guid';
COMMENT ON COLUMN users.status IS 'status';
COMMENT ON COLUMN users.created_at IS 'created_at';
COMMENT ON COLUMN users.updated_at IS 'updated_at';
COMMENT ON TABLE org_units IS '表: org_units';
COMMENT ON COLUMN org_units.id IS 'id';
COMMENT ON COLUMN org_units.parent_id IS 'parent_id';
COMMENT ON COLUMN org_units.name IS 'name';
COMMENT ON COLUMN org_units.short_name IS 'short_name';
COMMENT ON COLUMN org_units.type IS 'type';
COMMENT ON COLUMN org_units.sort_order IS 'sort_order';
COMMENT ON COLUMN org_units.status IS 'status';
COMMENT ON COLUMN org_units.phone IS 'phone';
COMMENT ON COLUMN org_units.email IS 'email';
COMMENT ON COLUMN org_units.created_at IS 'created_at';
COMMENT ON COLUMN org_units.updated_at IS 'updated_at';
COMMENT ON TABLE org_unit_leaders IS '表: org_unit_leaders';
COMMENT ON COLUMN org_unit_leaders.org_unit_id IS 'org_unit_id';
COMMENT ON COLUMN org_unit_leaders.user_id IS 'user_id';
COMMENT ON TABLE user_org_units IS '表: user_org_units';
COMMENT ON COLUMN user_org_units.user_id IS 'user_id';
COMMENT ON COLUMN user_org_units.org_unit_id IS 'org_unit_id';
COMMENT ON TABLE verification_email_settings IS '表: verification_email_settings';
COMMENT ON COLUMN verification_email_settings.id IS 'id';
COMMENT ON COLUMN verification_email_settings.email_enabled IS 'email_enabled';
COMMENT ON COLUMN verification_email_settings.email_host IS 'email_host';
COMMENT ON COLUMN verification_email_settings.email_port IS 'email_port';
COMMENT ON COLUMN verification_email_settings.email_username IS 'email_username';
COMMENT ON COLUMN verification_email_settings.email_password IS 'email_password';
COMMENT ON COLUMN verification_email_settings.email_from IS 'email_from';
COMMENT ON COLUMN verification_email_settings.email_ssl IS 'email_ssl';
COMMENT ON TABLE verification_sms_settings IS '表: verification_sms_settings';
COMMENT ON COLUMN verification_sms_settings.id IS 'id';
COMMENT ON COLUMN verification_sms_settings.sms_enabled IS 'sms_enabled';
COMMENT ON COLUMN verification_sms_settings.sms_provider IS 'sms_provider';
COMMENT ON COLUMN verification_sms_settings.sms_aliyun_enabled IS 'sms_aliyun_enabled';
COMMENT ON COLUMN verification_sms_settings.sms_aliyun_access_key_id IS 'sms_aliyun_access_key_id';
COMMENT ON COLUMN verification_sms_settings.sms_aliyun_access_key_secret IS 'sms_aliyun_access_key_secret';
COMMENT ON COLUMN verification_sms_settings.sms_aliyun_sign_name IS 'sms_aliyun_sign_name';
COMMENT ON COLUMN verification_sms_settings.sms_aliyun_template_code IS 'sms_aliyun_template_code';
COMMENT ON COLUMN verification_sms_settings.sms_aliyun_region_id IS 'sms_aliyun_region_id';
COMMENT ON COLUMN verification_sms_settings.sms_aliyun_endpoint IS 'sms_aliyun_endpoint';
COMMENT ON COLUMN verification_sms_settings.sms_tencent_enabled IS 'sms_tencent_enabled';
COMMENT ON COLUMN verification_sms_settings.sms_tencent_secret_id IS 'sms_tencent_secret_id';
COMMENT ON COLUMN verification_sms_settings.sms_tencent_secret_key IS 'sms_tencent_secret_key';
COMMENT ON COLUMN verification_sms_settings.sms_tencent_sign_name IS 'sms_tencent_sign_name';
COMMENT ON COLUMN verification_sms_settings.sms_tencent_template_id IS 'sms_tencent_template_id';
COMMENT ON COLUMN verification_sms_settings.sms_tencent_region IS 'sms_tencent_region';
COMMENT ON COLUMN verification_sms_settings.sms_tencent_endpoint IS 'sms_tencent_endpoint';
COMMENT ON COLUMN verification_sms_settings.sms_sdk_app_id IS 'sms_sdk_app_id';
COMMENT ON TABLE watermark_settings IS '表: watermark_settings';
COMMENT ON COLUMN watermark_settings.id IS 'id';
COMMENT ON COLUMN watermark_settings.type IS 'type';
COMMENT ON COLUMN watermark_settings.content IS 'content';
COMMENT ON COLUMN watermark_settings.image_url IS 'image_url';
COMMENT ON COLUMN watermark_settings.opacity IS 'opacity';
COMMENT ON COLUMN watermark_settings.size IS 'size';
COMMENT ON COLUMN watermark_settings.gap_x IS 'gap_x';
COMMENT ON COLUMN watermark_settings.gap_y IS 'gap_y';
COMMENT ON COLUMN watermark_settings.rotate IS 'rotate';
COMMENT ON COLUMN watermark_settings.enabled IS 'enabled';
