<template>
  <div>
    <t-form :data="form" layout="vertical" label-align="right" label-width="140px" @submit.prevent>
      <t-row :gutter="[24, 16]">
        <t-col :span="24"><t-form-item label="启用人机验证码" help="开启后用户在登录、注册等环节需要完成验证码验证"><t-switch v-model="form.captchaEnabled" @change="handleCaptchaEnabledChange" /></t-form-item></t-col>
        <t-col :xs="24" :sm="12"><t-form-item label="验证码类型" help="选择系统使用的验证码方式"><t-radio-group v-model="form.captchaType" :disabled="!form.captchaEnabled"><t-radio-button value="drag">图形拖动验证码</t-radio-button><t-radio-button value="image">图片验证码</t-radio-button></t-radio-group></t-form-item></t-col>
        <template v-if="form.captchaType === 'drag'"><t-col :xs="24" :sm="12"><t-form-item label="拖动验证码宽度（px）" help="拖拽图片验证码的显示宽度"><t-input-number v-model="form.dragCaptchaWidth" :min="200" :step="10" :disabled="!form.captchaEnabled" style="max-width: 500px; width: 100%" /></t-form-item></t-col><t-col :xs="24" :sm="12"><t-form-item label="拖动验证码高度（px）" help="拖拽图片验证码的显示高度"><t-input-number v-model="form.dragCaptchaHeight" :min="100" :step="10" :disabled="!form.captchaEnabled" style="max-width: 500px; width: 100%" /></t-form-item></t-col><t-col :xs="24" :sm="12"><t-form-item label="拖动通过阈值（%）" help="用户拖动误差允许的范围百分比"><t-input-number v-model="form.dragCaptchaThreshold" :min="70" :max="100" :step="1" :disabled="!form.captchaEnabled" style="max-width: 500px; width: 100%" /></t-form-item></t-col></template>
        <template v-else><t-col :xs="24" :sm="12"><t-form-item label="验证码长度" help="图片验证码的字符数量"><t-input-number v-model="form.imageCaptchaLength" :min="4" :max="8" :disabled="!form.captchaEnabled" style="max-width: 500px; width: 100%" /></t-form-item></t-col><t-col :xs="24" :sm="12"><t-form-item label="干扰线条数" help="图片验证码中的干扰线数量"><t-input-number v-model="form.imageCaptchaNoiseLines" :min="0" :max="12" :disabled="!form.captchaEnabled" style="max-width: 500px; width: 100%" /></t-form-item></t-col></template>
        <t-col :span="24"><security-toolbar :saving="saving" :can-edit="canEdit" @save="$emit('save')" /></t-col>
      </t-row>
    </t-form>
    <t-dialog :visible="disableConfirmVisible" header="确认关闭人机验证码" :confirm-btn="{ content: '我已知晓，关闭', theme: 'danger' }" :cancel-btn="{ content: '保持开启' }" @confirm="confirmDisableCaptcha" @cancel="cancelDisableCaptcha" @update:visible="(value) => { if (!value) cancelDisableCaptcha(); }"><div style="display: flex; flex-direction: column; gap: 16px; padding-top: 8px"><t-alert theme="error" variant="outline"><template #message><span style="font-weight: 600">关闭验证码可能导致严重的安全隐患</span></template></t-alert><div style="background: var(--td-bg-color-container-hover); padding: 12px 16px; border-radius: var(--td-radius-default);"><div style="margin-bottom: 8px; color: var(--td-text-color-secondary)">潜在风险包括：</div><ul style="padding-left: 20px; margin: 0; line-height: 1.8; color: var(--td-text-color-primary)"><li>系统更易遭受<strong>自动化暴力破解</strong>攻击</li><li>恶意用户可能<strong>批量注册</strong>垃圾账号</li><li>API 接口可能被<strong>滥用刷量</strong>，导致服务不稳定</li></ul></div></div></t-dialog>
  </div>
</template>
<script setup lang="ts">import SecurityToolbar from './SecurityToolbar.vue'; defineProps<{ form: Record<string, any>; saving: boolean; canEdit: boolean; disableConfirmVisible: boolean; handleCaptchaEnabledChange: (value: string | number | boolean) => void; confirmDisableCaptcha: () => void; cancelDisableCaptcha: () => void }>(); defineEmits(['save']);</script>
