CREATE TABLE IF NOT EXISTS verification_email_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_enabled SMALLINT,
  email_host VARCHAR(255),
  email_port INTEGER,
  email_username VARCHAR(128),
  email_password VARCHAR(256),
  email_from VARCHAR(128),
  email_ssl SMALLINT
);

INSERT INTO verification_email_settings (id) VALUES (1)
  ON CONFLICT DO NOTHING;
