CREATE TABLE verification_email_settings (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_enabled NUMBER(3),
  email_host VARCHAR2(255),
  email_port NUMBER(10),
  email_username VARCHAR2(128),
  email_password VARCHAR2(256),
  email_from VARCHAR2(128),
  email_ssl NUMBER(3)
);

INSERT INTO verification_email_settings (id)
SELECT 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM verification_email_settings WHERE id = 1);
