-- Oracle initialization script for TDesign
-- Use (SQL*Plus): @database/demo/tdesign_init_oracle.sql
-- Note: run on an empty schema or drop existing tables first.

CREATE TABLE users (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account VARCHAR2(64) NOT NULL UNIQUE,
  guid VARCHAR2(36) NOT NULL UNIQUE,
  name VARCHAR2(64) NOT NULL,
  password_hash VARCHAR2(100) NOT NULL,
  mobile VARCHAR2(20),
  email VARCHAR2(100),
  id_card VARCHAR2(32),
  id_type VARCHAR2(32),
  id_valid_from DATE,
  id_valid_to DATE,
  seat VARCHAR2(50),
  entity VARCHAR2(100),
  leader VARCHAR2(64),
  position VARCHAR2(64),
  join_day DATE,
  team VARCHAR2(255),
  gender VARCHAR2(10),
  nickname VARCHAR2(64),
  province_id NUMBER(10),
  province VARCHAR2(100),
  city_id NUMBER(10),
  city VARCHAR2(100),
  district_id NUMBER(10),
  district VARCHAR2(100),
  town_id NUMBER(10),
  town VARCHAR2(100),
  street_id NUMBER(10),
  street VARCHAR2(100),
  zip_code VARCHAR2(12),
  address VARCHAR2(255),
  introduction CLOB,
  avatar VARCHAR2(255),
  tags VARCHAR2(255),
  status NUMBER(3) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE areas (
  id NUMBER(10) PRIMARY KEY,
  parent_id NUMBER(10) DEFAULT 0 NOT NULL,
  name VARCHAR2(120) DEFAULT '' NOT NULL,
  zip_code VARCHAR2(12),
  level NUMBER(3) DEFAULT 1 NOT NULL
);

CREATE INDEX idx_areas_parent ON areas (parent_id);
CREATE INDEX idx_areas_level ON areas (level);

CREATE TABLE org_units (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id NUMBER(19),
  name VARCHAR2(128) NOT NULL,
  short_name VARCHAR2(64),
  type VARCHAR2(32) NOT NULL,
  sort_order NUMBER(10) DEFAULT 0 NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  phone VARCHAR2(32),
  email VARCHAR2(128),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE org_unit_leaders (
  org_unit_id NUMBER(19) NOT NULL,
  user_id NUMBER(19) NOT NULL,
  PRIMARY KEY (org_unit_id, user_id)
);

CREATE TABLE user_org_units (
  user_id NUMBER(19) NOT NULL,
  org_unit_id NUMBER(19) NOT NULL,
  PRIMARY KEY (user_id, org_unit_id)
);

CREATE TABLE roles (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL UNIQUE,
  description VARCHAR2(255)
);

CREATE TABLE user_roles (
  user_id NUMBER(19) NOT NULL,
  role VARCHAR2(64) NOT NULL,
  PRIMARY KEY (user_id, role)
);

CREATE TABLE role_permissions (
  role_id NUMBER(19) NOT NULL,
  permission VARCHAR2(128) NOT NULL,
  PRIMARY KEY (role_id, permission)
);

CREATE TABLE sys_menu_items (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id NUMBER(19),
  node_type VARCHAR2(16) NOT NULL,
  path VARCHAR2(255) NOT NULL,
  route_name VARCHAR2(128) NOT NULL,
  component VARCHAR2(255),
  redirect VARCHAR2(255),
  title_zh_cn VARCHAR2(64) NOT NULL,
  title_en_us VARCHAR2(64),
  icon VARCHAR2(64),
  hidden NUMBER(3) DEFAULT 0 NOT NULL,
  frame_src VARCHAR2(512),
  frame_blank NUMBER(3) DEFAULT 0 NOT NULL,
  enabled NUMBER(3) DEFAULT 1 NOT NULL,
  order_no NUMBER(10) DEFAULT 0 NOT NULL,
  actions VARCHAR2(128),
  version NUMBER(10) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_menu_items_route_name UNIQUE (route_name)
);

CREATE TABLE sys_dict (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  name VARCHAR2(64) NOT NULL,
  code VARCHAR2(64) NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  remark VARCHAR2(255),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_dict_code UNIQUE (code)
);

CREATE TABLE role_menus (
  role_id NUMBER(19) NOT NULL,
  menu_id NUMBER(19) NOT NULL,
  PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE ui_brand_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_name VARCHAR2(100),
  app_version VARCHAR2(50),
  logo_expanded_url VARCHAR2(255),
  logo_collapsed_url VARCHAR2(255),
  favicon_url VARCHAR2(255),
  qr_code_url VARCHAR2(255)
);

CREATE TABLE ui_layout_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  default_home VARCHAR2(255),
  show_footer NUMBER(3),
  is_sidebar_compact NUMBER(3),
  show_breadcrumb NUMBER(3),
  menu_auto_collapsed NUMBER(3),
  layout VARCHAR2(20),
  split_menu NUMBER(3),
  side_mode VARCHAR2(20),
  is_footer_aside NUMBER(3),
  is_sidebar_fixed NUMBER(3),
  is_header_fixed NUMBER(3),
  is_use_tabs_router NUMBER(3),
  show_header NUMBER(3)
);

CREATE TABLE ui_theme_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auto_theme NUMBER(3),
  light_start_time VARCHAR2(10),
  dark_start_time VARCHAR2(10),
  mode VARCHAR2(20),
  brand_theme VARCHAR2(20)
);

CREATE TABLE ui_footer_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  footer_company VARCHAR2(100),
  footer_icp VARCHAR2(100),
  copyright_start_year VARCHAR2(10)
);

CREATE TABLE ui_login_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_bg_url VARCHAR2(255),
  allow_multi_device_login NUMBER(3)
);

CREATE TABLE ui_legal_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_agreement CLOB,
  privacy_agreement CLOB
);

CREATE TABLE ui_system_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_retention_days NUMBER(10),
  ai_assistant_enabled NUMBER(3)
);

CREATE TABLE module_registry (
  module_key VARCHAR2(64) PRIMARY KEY,
  name VARCHAR2(128),
  version VARCHAR2(32),
  enabled NUMBER(3) DEFAULT 1,
  install_state VARCHAR2(32),
  installed_at DATE
);

CREATE TABLE security_token_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_timeout_minutes NUMBER(10),
  token_timeout_minutes NUMBER(10),
  token_refresh_grace_minutes NUMBER(10),
  allow_url_token_param NUMBER(3) DEFAULT 0 NOT NULL
);

CREATE TABLE security_captcha_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captcha_enabled NUMBER(3),
  captcha_type VARCHAR2(20),
  drag_captcha_width NUMBER(10),
  drag_captcha_height NUMBER(10),
  drag_captcha_threshold NUMBER(10),
  image_captcha_length NUMBER(10),
  image_captcha_noise_lines NUMBER(10)
);

CREATE TABLE security_password_policy (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password_min_length NUMBER(10),
  password_require_uppercase NUMBER(3),
  password_require_lowercase NUMBER(3),
  password_require_special NUMBER(3),
  password_allow_sequential NUMBER(3)
);

CREATE TABLE operation_logs (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR2(32) NOT NULL,
  module VARCHAR2(64),
  detail VARCHAR2(512),
  user_id NUMBER(19),
  user_guid VARCHAR2(36),
  account VARCHAR2(64),
  ip_address VARCHAR2(64),
  device_model VARCHAR2(128),
  os VARCHAR2(64),
  browser VARCHAR2(64),
  created_at TIMESTAMP
);

CREATE TABLE user_parameters (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER(19) NOT NULL,
  param_key VARCHAR2(100) NOT NULL,
  param_value CLOB NOT NULL,
  description VARCHAR2(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE storage_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR2(20) NOT NULL,
  bucket VARCHAR2(128),
  region VARCHAR2(128),
  endpoint VARCHAR2(255),
  access_key VARCHAR2(128),
  secret_key VARCHAR2(128),
  custom_domain VARCHAR2(255),
  path_prefix VARCHAR2(128),
  public_read NUMBER(3)
);

CREATE TABLE announcements (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  summary VARCHAR2(200),
  content CLOB NOT NULL,
  type VARCHAR2(32) NOT NULL,
  priority VARCHAR2(16) NOT NULL,
  status VARCHAR2(16) NOT NULL,
  cover_url VARCHAR2(255),
  attachment_url VARCHAR2(255),
  attachment_name VARCHAR2(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id NUMBER(19),
  created_by_name VARCHAR2(64),
  is_broadcasted NUMBER(3) DEFAULT 0 NOT NULL
);

CREATE TABLE notifications (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  summary VARCHAR2(200),
  content CLOB NOT NULL,
  priority VARCHAR2(16) NOT NULL,
  status VARCHAR2(16) NOT NULL,
  type VARCHAR2(32),
  cover_url VARCHAR2(512),
  attachment_url VARCHAR2(512),
  attachment_name VARCHAR2(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id NUMBER(19),
  created_by_name VARCHAR2(64)
);

CREATE TABLE ai_provider_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL,
  vendor VARCHAR2(32) NOT NULL,
  base_url VARCHAR2(255) NOT NULL,
  endpoint_path VARCHAR2(255),
  model VARCHAR2(128),
  api_key VARCHAR2(512),
  api_version VARCHAR2(64),
  temperature NUMBER,
  max_tokens NUMBER(10),
  is_default NUMBER(3),
  enabled NUMBER(3),
  extra_headers VARCHAR2(2000),
  remark VARCHAR2(512),
  last_test_status VARCHAR2(32),
  last_test_message VARCHAR2(512),
  last_tested_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_words (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word VARCHAR2(200) NOT NULL UNIQUE,
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_page_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_key VARCHAR2(255) NOT NULL UNIQUE,
  page_name VARCHAR2(255),
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled NUMBER(3) NOT NULL,
  updated_at TIMESTAMP
);

-- ----------------------------
-- Records of sys_dict
-- ----------------------------
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2001, '性别', 'gender', 1, 1, '性别选项', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2002, '证件-类型', 'id_document_type', 1, 2, '证件类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2004, '地址-区', 'address_district', 1, 4, '地址区县', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2005, '公告-类型', 'announcement_type', 1, 5, '公告类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2006, '公告-优先级', 'announcement_priority', 1, 6, '公告优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2007, '公告-状态', 'announcement_status', 1, 7, '公告状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2008, '通知-类型', 'notification_type', 1, 8, '通知类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2009, '通知-优先级', 'notification_priority', 1, 9, '通知优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2010, '通知-状态', 'notification_status', 1, 10, '通知状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2011, '消息-优先级', 'message_quality', 1, 11, '消息优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2012, '日志-操作类型', 'log_action', 1, 12, '操作日志类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2013, '用户-状态', 'user_status', 1, 13, '用户状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2014, '机构-类型', 'org_type', 1, 14, '机构类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2015, '机构-状态', 'org_status', 1, 15, '机构状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2016, '菜单-节点类型', 'menu_node_type', 1, 16, '菜单节点类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2017, '菜单-权限动作', 'menu_action', 1, 17, '菜单权限动作', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2018, '存储-提供商', 'storage_provider', 1, 18, '存储提供商', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2019, '短信-通道', 'sms_provider', 1, 19, '短信通道', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2020, 'AI-厂商', 'ai_vendor', 1, 20, 'AI厂商', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

-- Dictionary item tables (per dictionary)

CREATE TABLE sys_di_gender_de9feaea (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_gender_de9feaea (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2101, '男', 'male', 'string', 1, 1, 'success', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_gender_de9feaea (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2102, '女', 'female', 'string', 1, 2, 'danger', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_gender_de9feaea (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2103, '未知', 'unknown', 'string', 1, 3, 'warning', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_id_document_ty_e77fcd76 (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_id_document_ty_e77fcd76 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2201, '居民身份证', 'resident_id_card', 'string', 1, 1, 'success', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_id_document_ty_e77fcd76 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2202, '护照', 'passport', 'string', 1, 2, 'warning', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_address_distri_a4210592 (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  province VARCHAR2(128),
  city VARCHAR2(128),
  district VARCHAR2(128),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2401, '南山区', '南山区', 'string', 1, 1, NULL, '广东省', '深圳市', '南山区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2402, '福田区', '福田区', 'string', 1, 2, NULL, '广东省', '深圳市', '福田区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2403, '宝安区', '宝安区', 'string', 1, 3, NULL, '广东省', '深圳市', '宝安区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2404, '龙岗区', '龙岗区', 'string', 1, 4, NULL, '广东省', '深圳市', '龙岗区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2405, '龙华区', '龙华区', 'string', 1, 5, NULL, '广东省', '深圳市', '龙华区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2406, '天河区', '天河区', 'string', 1, 6, NULL, '广东省', '广州市', '天河区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2407, '越秀区', '越秀区', 'string', 1, 7, NULL, '广东省', '广州市', '越秀区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2408, '番禺区', '番禺区', 'string', 1, 8, NULL, '广东省', '广州市', '番禺区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2409, '海珠区', '海珠区', 'string', 1, 9, NULL, '广东省', '广州市', '海珠区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2410, '白云区', '白云区', 'string', 1, 10, NULL, '广东省', '广州市', '白云区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2411, '黄浦区', '黄浦区', 'string', 1, 11, NULL, '上海市', '上海市', '黄浦区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2412, '徐汇区', '徐汇区', 'string', 1, 12, NULL, '上海市', '上海市', '徐汇区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2413, '长宁区', '长宁区', 'string', 1, 13, NULL, '上海市', '上海市', '长宁区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2414, '静安区', '静安区', 'string', 1, 14, NULL, '上海市', '上海市', '静安区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2415, '浦东新区', '浦东新区', 'string', 1, 15, NULL, '上海市', '上海市', '浦东新区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2416, '东城区', '东城区', 'string', 1, 16, NULL, '北京市', '北京市', '东城区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2417, '西城区', '西城区', 'string', 1, 17, NULL, '北京市', '北京市', '西城区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2418, '朝阳区', '朝阳区', 'string', 1, 18, NULL, '北京市', '北京市', '朝阳区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2419, '海淀区', '海淀区', 'string', 1, 19, NULL, '北京市', '北京市', '海淀区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2420, '西湖区', '西湖区', 'string', 1, 20, NULL, '浙江省', '杭州市', '西湖区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2421, '上城区', '上城区', 'string', 1, 21, NULL, '浙江省', '杭州市', '上城区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2422, '下城区', '下城区', 'string', 1, 22, NULL, '浙江省', '杭州市', '下城区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2423, '江干区', '江干区', 'string', 1, 23, NULL, '浙江省', '杭州市', '江干区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
CREATE TABLE sys_di_announcement_t_de30e733 (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_announcement_t_de30e733 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2501, '公告', 'announcement', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_announcement_p_ef193e74 (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_announcement_p_ef193e74 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2511, '高', 'high', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_announcement_p_ef193e74 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2512, '中', 'middle', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_announcement_p_ef193e74 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2513, '低', 'low', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_announcement_s_f91c61fe (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_announcement_s_f91c61fe (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2521, '草稿', 'draft', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_announcement_s_f91c61fe (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2522, '已发布', 'published', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_announcement_s_f91c61fe (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2523, '已撤回', 'withdrawn', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_notification_t_301379fe (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_notification_t_301379fe (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2601, '通知', 'notification', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_notification_p_d682ffca (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_notification_p_d682ffca (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2611, '高', 'high', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_notification_p_d682ffca (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2612, '中', 'middle', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_notification_p_d682ffca (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2613, '低', 'low', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_notification_s_32716fa4 (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_notification_s_32716fa4 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2621, '草稿', 'draft', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_notification_s_32716fa4 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2622, '已发布', 'published', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_notification_s_32716fa4 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2623, '已撤回', 'withdrawn', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_message_qualit_6ab11001 (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_message_qualit_6ab11001 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2701, '高', 'high', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_message_qualit_6ab11001 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2702, '中', 'middle', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_message_qualit_6ab11001 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2703, '低', 'low', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_log_action_8705ceac (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_log_action_8705ceac (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2801, '登录', 'LOGIN', 'string', 1, 1, 'primary', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_log_action_8705ceac (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2802, '新增', 'CREATE', 'string', 1, 2, 'success', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_log_action_8705ceac (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2803, '修改', 'UPDATE', 'string', 1, 3, 'warning', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_log_action_8705ceac (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2804, '删除', 'DELETE', 'string', 1, 4, 'danger', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_user_status_e4abeb4f (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_user_status_e4abeb4f (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2901, '正常', '1', 'number', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_user_status_e4abeb4f (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2902, '停用', '0', 'number', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_org_type_5a06609e (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3001, '单位', 'UNIT', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3002, '部门', 'DEPARTMENT', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3003, '科室', 'SECTION', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3004, '班组', 'TEAM', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3005, '用户', 'USER', 'string', 1, 5, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_org_status_adc56f2a (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_org_status_adc56f2a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3011, '正常', '1', 'number', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_status_adc56f2a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3012, '停用', '0', 'number', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_menu_node_type_83d1630e (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_menu_node_type_83d1630e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3101, '目录', 'DIR', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_node_type_83d1630e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3102, '页面', 'PAGE', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_node_type_83d1630e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3103, '按钮', 'BTN', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_menu_action_6118cb39 (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_menu_action_6118cb39 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3201, '查询', 'query', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_action_6118cb39 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3202, '新增', 'create', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_action_6118cb39 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3203, '修改', 'update', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_action_6118cb39 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3204, '删除', 'delete', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_storage_provid_f9bb387a (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_storage_provid_f9bb387a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3301, '本地存储', 'LOCAL', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_storage_provid_f9bb387a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3302, '阿里云 OSS', 'ALIYUN', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_storage_provid_f9bb387a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3303, '腾讯云 COS', 'TENCENT', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_sms_provider_d65c9878 (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_sms_provider_d65c9878 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3401, '阿里云短信服务', 'aliyun', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_sms_provider_d65c9878 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3402, '腾讯云短信服务', 'tencent', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE sys_di_ai_vendor_f0a49eba (
  id NUMBER(19) PRIMARY KEY,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  label VARCHAR2(64) NOT NULL,
  value VARCHAR2(128) NOT NULL UNIQUE,
  value_type VARCHAR2(16) DEFAULT 'string' NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  tag_color VARCHAR2(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3501, 'OpenAI / 兼容', 'OPENAI', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3502, 'Azure OpenAI', 'AZURE_OPENAI', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3503, 'DeepSeek', 'DEEPSEEK', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3504, '月之暗面 / Moonshot', 'MOONSHOT', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3505, '通义千问 (兼容模式)', 'QWEN', 'string', 1, 5, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3506, 'Ollama 本地部署', 'OLLAMA', 'string', 1, 6, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');



-- ----------------------------
-- ----------------------------

-- Demo users/roles
INSERT INTO roles (id, name, description)
SELECT 1, 'admin', '管理员 - 拥有所有权限' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE id = 1);

INSERT INTO users (id, account, guid, name, password_hash, status, created_at, updated_at)
SELECT
  1,
  'admin',
  'e59c3cd1-3b52-47c7-bf88-fad5b2281827',
  '管理员',
  '$2a$10$BbVSQCIChdR.4gfwiG1OduJiKE/KpUTbhBXd.7Sr.uwi8eggDpYeu',
  1,
  SYSTIMESTAMP,
  SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE id = 1);

INSERT INTO user_roles (user_id, role)
SELECT 1, 'admin' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM user_roles WHERE user_id = 1 AND role = 'admin');

INSERT INTO module_registry (module_key, name, version, enabled, install_state, installed_at) VALUES ('sms', '短信验证', '1.0.0', 1, 'PENDING', NULL);
INSERT INTO module_registry (module_key, name, version, enabled, install_state, installed_at) VALUES ('email', '邮箱验证', '1.0.0', 1, 'PENDING', NULL);


