-- Oracle initialization script for TDesign
-- Use (SQL*Plus): @database/demo/tdesign_init_oracle.sql
-- Note: run on an empty schema or drop existing tables first.

CREATE TABLE users (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account VARCHAR2(64) NOT NULL UNIQUE,
  guid VARCHAR2(36) NOT NULL UNIQUE,
  name VARCHAR2(64) NOT NULL,
  password_hash VARCHAR2(100) NOT NULL,
  mobile VARCHAR2(20),
  phone VARCHAR2(20),
  email VARCHAR2(100),
  id_card VARCHAR2(32),
  seat VARCHAR2(50),
  entity VARCHAR2(100),
  leader VARCHAR2(64),
  position VARCHAR2(64),
  join_day DATE,
  team VARCHAR2(255),
  gender VARCHAR2(10),
  nickname VARCHAR2(64),
  province_id NUMBER(10),
  province VARCHAR2(100),
  city_id NUMBER(10),
  city VARCHAR2(100),
  district_id NUMBER(10),
  district VARCHAR2(100),
  town_id NUMBER(10),
  town VARCHAR2(100),
  street_id NUMBER(10),
  street VARCHAR2(100),
  zip_code VARCHAR2(12),
  address VARCHAR2(255),
  introduction CLOB,
  avatar VARCHAR2(255),
  tags VARCHAR2(255),
  status NUMBER(3) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE areas (
  id NUMBER(10) PRIMARY KEY,
  parent_id NUMBER(10) DEFAULT 0 NOT NULL,
  name VARCHAR2(120) DEFAULT '' NOT NULL,
  zip_code VARCHAR2(12),
  level NUMBER(3) DEFAULT 1 NOT NULL
);

CREATE INDEX idx_areas_parent ON areas (parent_id);
CREATE INDEX idx_areas_level ON areas (level);

CREATE TABLE org_units (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id NUMBER(19),
  name VARCHAR2(128) NOT NULL,
  short_name VARCHAR2(64),
  type VARCHAR2(32) NOT NULL,
  sort_order NUMBER(10) DEFAULT 0 NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  phone VARCHAR2(32),
  email VARCHAR2(128),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE org_unit_leaders (
  org_unit_id NUMBER(19) NOT NULL,
  user_id NUMBER(19) NOT NULL,
  PRIMARY KEY (org_unit_id, user_id)
);

CREATE TABLE user_org_units (
  user_id NUMBER(19) NOT NULL,
  org_unit_id NUMBER(19) NOT NULL,
  PRIMARY KEY (user_id, org_unit_id)
);

CREATE TABLE roles (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL UNIQUE,
  description VARCHAR2(255)
);

CREATE TABLE user_roles (
  user_id NUMBER(19) NOT NULL,
  role VARCHAR2(64) NOT NULL,
  PRIMARY KEY (user_id, role)
);

CREATE TABLE role_permissions (
  role_id NUMBER(19) NOT NULL,
  permission VARCHAR2(128) NOT NULL,
  PRIMARY KEY (role_id, permission)
);

CREATE TABLE sys_menu_items (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id NUMBER(19),
  node_type VARCHAR2(16) NOT NULL,
  path VARCHAR2(255) NOT NULL,
  route_name VARCHAR2(128) NOT NULL,
  component VARCHAR2(255),
  redirect VARCHAR2(255),
  title_zh_cn VARCHAR2(64) NOT NULL,
  title_en_us VARCHAR2(64),
  icon VARCHAR2(64),
  hidden NUMBER(3) DEFAULT 0 NOT NULL,
  frame_src VARCHAR2(512),
  frame_blank NUMBER(3) DEFAULT 0 NOT NULL,
  enabled NUMBER(3) DEFAULT 1 NOT NULL,
  order_no NUMBER(10) DEFAULT 0 NOT NULL,
  actions VARCHAR2(128),
  version NUMBER(10) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_menu_items_route_name UNIQUE (route_name)
);

CREATE TABLE sys_dict (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL,
  code VARCHAR2(64) NOT NULL,
  status NUMBER(3) DEFAULT 1 NOT NULL,
  sort NUMBER(10) DEFAULT 0 NOT NULL,
  remark VARCHAR2(255),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_sys_dict_code UNIQUE (code)
);

CREATE TABLE role_menus (
  role_id NUMBER(19) NOT NULL,
  menu_id NUMBER(19) NOT NULL,
  PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE ui_brand_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_name VARCHAR2(100),
  app_version VARCHAR2(50),
  logo_expanded_url VARCHAR2(255),
  logo_collapsed_url VARCHAR2(255),
  favicon_url VARCHAR2(255),
  qr_code_url VARCHAR2(255)
);

CREATE TABLE ui_layout_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  default_home VARCHAR2(255),
  show_footer NUMBER(3),
  is_sidebar_compact NUMBER(3),
  show_breadcrumb NUMBER(3),
  menu_auto_collapsed NUMBER(3),
  layout VARCHAR2(20),
  split_menu NUMBER(3),
  side_mode VARCHAR2(20),
  is_footer_aside NUMBER(3),
  is_sidebar_fixed NUMBER(3),
  is_header_fixed NUMBER(3),
  is_use_tabs_router NUMBER(3),
  show_header NUMBER(3)
);

CREATE TABLE ui_theme_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auto_theme NUMBER(3),
  light_start_time VARCHAR2(10),
  dark_start_time VARCHAR2(10),
  mode VARCHAR2(20),
  brand_theme VARCHAR2(20)
);

CREATE TABLE ui_footer_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  footer_company VARCHAR2(100),
  footer_icp VARCHAR2(100),
  copyright_start_year VARCHAR2(10)
);

CREATE TABLE ui_login_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_bg_url VARCHAR2(255),
  allow_multi_device_login NUMBER(3)
);

CREATE TABLE ui_legal_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_agreement CLOB,
  privacy_agreement CLOB
);

CREATE TABLE ui_system_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_retention_days NUMBER(10),
  ai_assistant_enabled NUMBER(3)
);

CREATE TABLE module_registry (
  module_key VARCHAR2(64) PRIMARY KEY,
  name VARCHAR2(128),
  version VARCHAR2(32),
  enabled NUMBER(3) DEFAULT 1,
  install_state VARCHAR2(32),
  installed_at DATE
);

CREATE TABLE security_token_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_timeout_minutes NUMBER(10),
  token_timeout_minutes NUMBER(10),
  token_refresh_grace_minutes NUMBER(10),
  allow_url_token_param NUMBER(3) DEFAULT 0 NOT NULL
);

CREATE TABLE security_captcha_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captcha_enabled NUMBER(3),
  captcha_type VARCHAR2(20),
  drag_captcha_width NUMBER(10),
  drag_captcha_height NUMBER(10),
  drag_captcha_threshold NUMBER(10),
  image_captcha_length NUMBER(10),
  image_captcha_noise_lines NUMBER(10)
);

CREATE TABLE security_password_policy (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password_min_length NUMBER(10),
  password_require_uppercase NUMBER(3),
  password_require_lowercase NUMBER(3),
  password_require_special NUMBER(3),
  password_allow_sequential NUMBER(3)
);

CREATE TABLE operation_logs (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR2(32) NOT NULL,
  module VARCHAR2(64),
  detail VARCHAR2(512),
  user_id NUMBER(19),
  user_guid VARCHAR2(36),
  account VARCHAR2(64),
  ip_address VARCHAR2(64),
  device_model VARCHAR2(128),
  os VARCHAR2(64),
  browser VARCHAR2(64),
  created_at TIMESTAMP
);

CREATE TABLE user_parameters (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER(19) NOT NULL,
  param_key VARCHAR2(100) NOT NULL,
  param_value CLOB NOT NULL,
  description VARCHAR2(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE storage_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR2(20) NOT NULL,
  bucket VARCHAR2(128),
  region VARCHAR2(128),
  endpoint VARCHAR2(255),
  access_key VARCHAR2(128),
  secret_key VARCHAR2(128),
  custom_domain VARCHAR2(255),
  path_prefix VARCHAR2(128),
  public_read NUMBER(3)
);

CREATE TABLE announcements (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  summary VARCHAR2(200),
  content CLOB NOT NULL,
  type VARCHAR2(32) NOT NULL,
  priority VARCHAR2(16) NOT NULL,
  status VARCHAR2(16) NOT NULL,
  cover_url VARCHAR2(255),
  attachment_url VARCHAR2(255),
  attachment_name VARCHAR2(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id NUMBER(19),
  created_by_name VARCHAR2(64),
  is_broadcasted NUMBER(3) DEFAULT 0 NOT NULL
);

CREATE TABLE notifications (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  summary VARCHAR2(200),
  content CLOB NOT NULL,
  priority VARCHAR2(16) NOT NULL,
  status VARCHAR2(16) NOT NULL,
  type VARCHAR2(32),
  cover_url VARCHAR2(512),
  attachment_url VARCHAR2(512),
  attachment_name VARCHAR2(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id NUMBER(19),
  created_by_name VARCHAR2(64)
);

CREATE TABLE ai_provider_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL,
  vendor VARCHAR2(32) NOT NULL,
  base_url VARCHAR2(255) NOT NULL,
  endpoint_path VARCHAR2(255),
  model VARCHAR2(128),
  api_key VARCHAR2(512),
  api_version VARCHAR2(64),
  temperature NUMBER,
  max_tokens NUMBER(10),
  is_default NUMBER(3),
  enabled NUMBER(3),
  extra_headers VARCHAR2(2000),
  remark VARCHAR2(512),
  last_test_status VARCHAR2(32),
  last_test_message VARCHAR2(512),
  last_tested_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_words (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word VARCHAR2(200) NOT NULL UNIQUE,
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_page_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_key VARCHAR2(255) NOT NULL UNIQUE,
  page_name VARCHAR2(255),
  enabled NUMBER(3) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE sensitive_settings (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled NUMBER(3) NOT NULL,
  updated_at TIMESTAMP
);

-- ----------------------------
-- Records of sys_dict
-- ----------------------------
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2001, '性别', 'gender', 1, 1, '性别选项', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2002, '地址-省', 'address_province', 1, 2, '地址省份', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2003, '地址-市', 'address_city', 1, 3, '地址城市', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2004, '地址-区', 'address_district', 1, 4, '地址区县', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2005, '公告-类型', 'announcement_type', 1, 5, '公告类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2006, '公告-优先级', 'announcement_priority', 1, 6, '公告优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2007, '公告-状态', 'announcement_status', 1, 7, '公告状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2008, '通知-类型', 'notification_type', 1, 8, '通知类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2009, '通知-优先级', 'notification_priority', 1, 9, '通知优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2010, '通知-状态', 'notification_status', 1, 10, '通知状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2011, '消息-优先级', 'message_quality', 1, 11, '消息优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2012, '日志-操作类型', 'log_action', 1, 12, '操作日志类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2013, '用户-状态', 'user_status', 1, 13, '用户状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2014, '机构-类型', 'org_type', 1, 14, '机构类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2015, '机构-状态', 'org_status', 1, 15, '机构状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2016, '菜单-节点类型', 'menu_node_type', 1, 16, '菜单节点类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2017, '菜单-权限动作', 'menu_action', 1, 17, '菜单权限动作', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2018, '存储-提供商', 'storage_provider', 1, 18, '存储提供商', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2019, '短信-通道', 'sms_provider', 1, 19, '短信通道', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2020, 'AI-厂商', 'ai_vendor', 1, 20, 'AI厂商', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES (2021, '团队', 'team', 1, 21, '团队管理', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

-- ----------------------------
-- ----------------------------

-- Demo users/roles
INSERT INTO roles (id, name, description)
SELECT 1, 'admin', '管理员 - 拥有所有权限' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE id = 1);

INSERT INTO users (id, account, guid, name, password_hash, status, created_at, updated_at)
SELECT
  1,
  'admin',
  'e59c3cd1-3b52-47c7-bf88-fad5b2281827',
  '管理员',
  '$2a$10$BbVSQCIChdR.4gfwiG1OduJiKE/KpUTbhBXd.7Sr.uwi8eggDpYeu',
  1,
  SYSTIMESTAMP,
  SYSTIMESTAMP
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE id = 1);

INSERT INTO user_roles (user_id, role)
SELECT 1, 'admin' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM user_roles WHERE user_id = 1 AND role = 'admin');

INSERT INTO module_registry (module_key, name, version, enabled, install_state, installed_at) VALUES ('sms', '短信验证', '1.0.0', 1, 'PENDING', NULL);
INSERT INTO module_registry (module_key, name, version, enabled, install_state, installed_at) VALUES ('email', '邮箱验证', '1.0.0', 1, 'PENDING', NULL);


