-- PostgreSQL initialization script for TDesign
-- Use: psql -d tdesign -f database/demo/tdesign_init_pg.sql

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account VARCHAR(64) NOT NULL UNIQUE,
  guid VARCHAR(36) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  mobile VARCHAR(20),
  email VARCHAR(100),
  id_card VARCHAR(32),
  id_type VARCHAR(32),
  id_valid_from DATE,
  id_valid_to DATE,
  seat VARCHAR(50),
  entity VARCHAR(100),
  leader VARCHAR(64),
  position VARCHAR(64),
  join_day DATE,
  team VARCHAR(255),
  gender VARCHAR(10),
  nickname VARCHAR(64),
  province_id INTEGER,
  province VARCHAR(100),
  city_id INTEGER,
  city VARCHAR(100),
  district_id INTEGER,
  district VARCHAR(100),
  town_id INTEGER,
  town VARCHAR(100),
  street_id INTEGER,
  street VARCHAR(100),
  zip_code VARCHAR(12),
  address VARCHAR(255),
  introduction TEXT,
  avatar VARCHAR(255),
  tags VARCHAR(255),
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS areas (
  id INTEGER PRIMARY KEY,
  parent_id INTEGER NOT NULL DEFAULT 0,
  name VARCHAR(120) NOT NULL DEFAULT '',
  zip_code VARCHAR(12),
  level SMALLINT NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_areas_parent ON areas (parent_id);
CREATE INDEX IF NOT EXISTS idx_areas_level ON areas (level);

CREATE TABLE IF NOT EXISTS org_units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT,
  name VARCHAR(128) NOT NULL,
  short_name VARCHAR(64),
  type VARCHAR(32) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  phone VARCHAR(32),
  email VARCHAR(128),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS org_unit_leaders (
  org_unit_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  PRIMARY KEY (org_unit_id, user_id)
);

CREATE TABLE IF NOT EXISTS user_org_units (
  user_id BIGINT NOT NULL,
  org_unit_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, org_unit_id)
);

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(64) UNIQUE NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT NOT NULL,
  role VARCHAR(64) NOT NULL,
  PRIMARY KEY (user_id, role)
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id BIGINT NOT NULL,
  permission VARCHAR(128) NOT NULL,
  PRIMARY KEY (role_id, permission)
);

CREATE TABLE IF NOT EXISTS sys_menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT,
  node_type VARCHAR(16) NOT NULL,
  path VARCHAR(255) NOT NULL,
  route_name VARCHAR(128) NOT NULL,
  component VARCHAR(255),
  redirect VARCHAR(255),
  title_zh_cn VARCHAR(64) NOT NULL,
  title_en_us VARCHAR(64),
  icon VARCHAR(64),
  hidden SMALLINT NOT NULL DEFAULT 0,
  frame_src VARCHAR(512),
  frame_blank SMALLINT NOT NULL DEFAULT 0,
  enabled SMALLINT NOT NULL DEFAULT 1,
  order_no INTEGER NOT NULL DEFAULT 0,
  actions VARCHAR(128),
  version INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_sys_menu_items_route_name UNIQUE (route_name)
);

CREATE TABLE IF NOT EXISTS sys_dict (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  name VARCHAR(64) NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_menus (
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE IF NOT EXISTS ui_brand_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_name VARCHAR(100),
  app_version VARCHAR(50),
  logo_expanded_url VARCHAR(255),
  logo_collapsed_url VARCHAR(255),
  favicon_url VARCHAR(255),
  qr_code_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ui_layout_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  default_home VARCHAR(255),
  show_footer SMALLINT,
  is_sidebar_compact SMALLINT,
  show_breadcrumb SMALLINT,
  menu_auto_collapsed SMALLINT,
  layout VARCHAR(20),
  split_menu SMALLINT,
  side_mode VARCHAR(20),
  is_footer_aside SMALLINT,
  is_sidebar_fixed SMALLINT,
  is_header_fixed SMALLINT,
  is_use_tabs_router SMALLINT,
  show_header SMALLINT
);

CREATE TABLE IF NOT EXISTS ui_theme_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auto_theme SMALLINT,
  light_start_time VARCHAR(10),
  dark_start_time VARCHAR(10),
  mode VARCHAR(20),
  brand_theme VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS ui_footer_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  footer_company VARCHAR(100),
  footer_icp VARCHAR(100),
  copyright_start_year VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS ui_login_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_bg_url VARCHAR(255),
  allow_multi_device_login SMALLINT
);

CREATE TABLE IF NOT EXISTS ui_legal_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_agreement TEXT,
  privacy_agreement TEXT
);

CREATE TABLE IF NOT EXISTS ui_system_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_retention_days INTEGER,
  ai_assistant_enabled SMALLINT
);

CREATE TABLE IF NOT EXISTS module_registry (
  module_key VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128),
  version VARCHAR(32),
  enabled SMALLINT DEFAULT 1,
  install_state VARCHAR(32),
  installed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS security_token_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_timeout_minutes INTEGER,
  token_timeout_minutes INTEGER,
  token_refresh_grace_minutes INTEGER,
  allow_url_token_param SMALLINT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS security_captcha_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captcha_enabled SMALLINT,
  captcha_type VARCHAR(20),
  drag_captcha_width INTEGER,
  drag_captcha_height INTEGER,
  drag_captcha_threshold INTEGER,
  image_captcha_length INTEGER,
  image_captcha_noise_lines INTEGER
);

CREATE TABLE IF NOT EXISTS security_password_policy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password_min_length INTEGER,
  password_require_uppercase SMALLINT,
  password_require_lowercase SMALLINT,
  password_require_special SMALLINT,
  password_allow_sequential SMALLINT
);

CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(32) NOT NULL,
  module VARCHAR(64),
  detail VARCHAR(512),
  user_id BIGINT,
  user_guid VARCHAR(36),
  account VARCHAR(64),
  ip_address VARCHAR(64),
  device_model VARCHAR(128),
  os VARCHAR(64),
  browser VARCHAR(64),
  created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_parameters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  param_key VARCHAR(100) NOT NULL,
  param_value TEXT NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS storage_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(20) NOT NULL,
  bucket VARCHAR(128),
  region VARCHAR(128),
  endpoint VARCHAR(255),
  access_key VARCHAR(128),
  secret_key VARCHAR(128),
  custom_domain VARCHAR(255),
  path_prefix VARCHAR(128),
  public_read SMALLINT
);

CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  summary VARCHAR(200),
  content TEXT NOT NULL,
  type VARCHAR(32) NOT NULL,
  priority VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  cover_url VARCHAR(255),
  attachment_url VARCHAR(255),
  attachment_name VARCHAR(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id BIGINT,
  created_by_name VARCHAR(64),
  is_broadcasted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  summary VARCHAR(200),
  content TEXT NOT NULL,
  priority VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  type VARCHAR(32),
  cover_url VARCHAR(512),
  attachment_url VARCHAR(512),
  attachment_name VARCHAR(255),
  publish_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by_id BIGINT,
  created_by_name VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS ai_provider_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  vendor VARCHAR(32) NOT NULL,
  base_url VARCHAR(255) NOT NULL,
  endpoint_path VARCHAR(255),
  model VARCHAR(128),
  api_key VARCHAR(512),
  api_version VARCHAR(64),
  temperature DOUBLE PRECISION,
  max_tokens INTEGER,
  is_default SMALLINT,
  enabled SMALLINT,
  extra_headers VARCHAR(2000),
  remark VARCHAR(512),
  last_test_status VARCHAR(32),
  last_test_message VARCHAR(512),
  last_tested_at TIMESTAMP,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sensitive_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word VARCHAR(200) NOT NULL UNIQUE,
  enabled SMALLINT NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sensitive_page_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_key VARCHAR(255) NOT NULL UNIQUE,
  page_name VARCHAR(255),
  enabled SMALLINT NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sensitive_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled SMALLINT NOT NULL,
  updated_at TIMESTAMP
);

-- ----------------------------
-- Records of sys_dict
-- ----------------------------
INSERT INTO sys_dict (id, name, code, status, sort, remark, created_at, updated_at) VALUES
  (2001, '性别', 'gender', 1, 1, '性别选项', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2002, '证件-类型', 'id_document_type', 1, 2, '证件类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2004, '地址-区', 'address_district', 1, 4, '地址区县', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2005, '公告-类型', 'announcement_type', 1, 5, '公告类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2006, '公告-优先级', 'announcement_priority', 1, 6, '公告优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2007, '公告-状态', 'announcement_status', 1, 7, '公告状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2008, '通知-类型', 'notification_type', 1, 8, '通知类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2009, '通知-优先级', 'notification_priority', 1, 9, '通知优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2010, '通知-状态', 'notification_status', 1, 10, '通知状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2011, '消息-优先级', 'message_quality', 1, 11, '消息优先级', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2012, '日志-操作类型', 'log_action', 1, 12, '操作日志类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2013, '用户-状态', 'user_status', 1, 13, '用户状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2014, '机构-类型', 'org_type', 1, 14, '机构类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2015, '机构-状态', 'org_status', 1, 15, '机构状态', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2016, '菜单-节点类型', 'menu_node_type', 1, 16, '菜单节点类型', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2017, '菜单-权限动作', 'menu_action', 1, 17, '菜单权限动作', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2018, '存储-提供商', 'storage_provider', 1, 18, '存储提供商', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2019, '短信-通道', 'sms_provider', 1, 19, '短信通道', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03'),
  (2020, 'AI-厂商', 'ai_vendor', 1, 20, 'AI厂商', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

-- Dictionary item tables (per dictionary)

CREATE TABLE IF NOT EXISTS sys_di_gender_de9feaea (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_gender_de9feaea (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2101, '男', 'male', 'string', 1, 1, 'success', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_gender_de9feaea (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2102, '女', 'female', 'string', 1, 2, 'danger', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_gender_de9feaea (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2103, '未知', 'unknown', 'string', 1, 3, 'warning', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_id_document_ty_e77fcd76 (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_id_document_ty_e77fcd76 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2201, '居民身份证', 'resident_id_card', 'string', 1, 1, 'success', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_id_document_ty_e77fcd76 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2202, '护照', 'passport', 'string', 1, 2, 'warning', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_address_distri_a4210592 (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  province VARCHAR(128),
  city VARCHAR(128),
  district VARCHAR(128),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2401, '南山区', '南山区', 'string', 1, 1, NULL, '广东省', '深圳市', '南山区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2402, '福田区', '福田区', 'string', 1, 2, NULL, '广东省', '深圳市', '福田区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2403, '宝安区', '宝安区', 'string', 1, 3, NULL, '广东省', '深圳市', '宝安区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2404, '龙岗区', '龙岗区', 'string', 1, 4, NULL, '广东省', '深圳市', '龙岗区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2405, '龙华区', '龙华区', 'string', 1, 5, NULL, '广东省', '深圳市', '龙华区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2406, '天河区', '天河区', 'string', 1, 6, NULL, '广东省', '广州市', '天河区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2407, '越秀区', '越秀区', 'string', 1, 7, NULL, '广东省', '广州市', '越秀区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2408, '番禺区', '番禺区', 'string', 1, 8, NULL, '广东省', '广州市', '番禺区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2409, '海珠区', '海珠区', 'string', 1, 9, NULL, '广东省', '广州市', '海珠区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2410, '白云区', '白云区', 'string', 1, 10, NULL, '广东省', '广州市', '白云区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2411, '黄浦区', '黄浦区', 'string', 1, 11, NULL, '上海市', '上海市', '黄浦区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2412, '徐汇区', '徐汇区', 'string', 1, 12, NULL, '上海市', '上海市', '徐汇区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2413, '长宁区', '长宁区', 'string', 1, 13, NULL, '上海市', '上海市', '长宁区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2414, '静安区', '静安区', 'string', 1, 14, NULL, '上海市', '上海市', '静安区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2415, '浦东新区', '浦东新区', 'string', 1, 15, NULL, '上海市', '上海市', '浦东新区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2416, '东城区', '东城区', 'string', 1, 16, NULL, '北京市', '北京市', '东城区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2417, '西城区', '西城区', 'string', 1, 17, NULL, '北京市', '北京市', '西城区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2418, '朝阳区', '朝阳区', 'string', 1, 18, NULL, '北京市', '北京市', '朝阳区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2419, '海淀区', '海淀区', 'string', 1, 19, NULL, '北京市', '北京市', '海淀区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2420, '西湖区', '西湖区', 'string', 1, 20, NULL, '浙江省', '杭州市', '西湖区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2421, '上城区', '上城区', 'string', 1, 21, NULL, '浙江省', '杭州市', '上城区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2422, '下城区', '下城区', 'string', 1, 22, NULL, '浙江省', '杭州市', '下城区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_address_distri_a4210592 (id, label, value, value_type, status, sort, tag_color, province, city, district, created_at, updated_at) VALUES (2423, '江干区', '江干区', 'string', 1, 23, NULL, '浙江省', '杭州市', '江干区', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
CREATE TABLE IF NOT EXISTS sys_di_announcement_t_de30e733 (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_announcement_t_de30e733 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2501, '公告', 'announcement', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_announcement_p_ef193e74 (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_announcement_p_ef193e74 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2511, '高', 'high', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_announcement_p_ef193e74 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2512, '中', 'middle', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_announcement_p_ef193e74 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2513, '低', 'low', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_announcement_s_f91c61fe (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_announcement_s_f91c61fe (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2521, '草稿', 'draft', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_announcement_s_f91c61fe (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2522, '已发布', 'published', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_announcement_s_f91c61fe (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2523, '已撤回', 'withdrawn', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_notification_t_301379fe (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_notification_t_301379fe (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2601, '通知', 'notification', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_notification_p_d682ffca (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_notification_p_d682ffca (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2611, '高', 'high', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_notification_p_d682ffca (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2612, '中', 'middle', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_notification_p_d682ffca (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2613, '低', 'low', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_notification_s_32716fa4 (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_notification_s_32716fa4 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2621, '草稿', 'draft', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_notification_s_32716fa4 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2622, '已发布', 'published', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_notification_s_32716fa4 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2623, '已撤回', 'withdrawn', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_message_qualit_6ab11001 (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_message_qualit_6ab11001 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2701, '高', 'high', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_message_qualit_6ab11001 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2702, '中', 'middle', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_message_qualit_6ab11001 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2703, '低', 'low', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_log_action_8705ceac (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_log_action_8705ceac (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2801, '登录', 'LOGIN', 'string', 1, 1, 'primary', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_log_action_8705ceac (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2802, '新增', 'CREATE', 'string', 1, 2, 'success', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_log_action_8705ceac (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2803, '修改', 'UPDATE', 'string', 1, 3, 'warning', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_log_action_8705ceac (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2804, '删除', 'DELETE', 'string', 1, 4, 'danger', TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_user_status_e4abeb4f (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_user_status_e4abeb4f (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2901, '正常', '1', 'number', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_user_status_e4abeb4f (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (2902, '停用', '0', 'number', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_org_type_5a06609e (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3001, '单位', 'UNIT', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3002, '部门', 'DEPARTMENT', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3003, '科室', 'SECTION', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3004, '班组', 'TEAM', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_type_5a06609e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3005, '用户', 'USER', 'string', 1, 5, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_org_status_adc56f2a (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_org_status_adc56f2a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3011, '正常', '1', 'number', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_org_status_adc56f2a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3012, '停用', '0', 'number', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_menu_node_type_83d1630e (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_menu_node_type_83d1630e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3101, '目录', 'DIR', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_node_type_83d1630e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3102, '页面', 'PAGE', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_node_type_83d1630e (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3103, '按钮', 'BTN', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_menu_action_6118cb39 (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_menu_action_6118cb39 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3201, '查询', 'query', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_action_6118cb39 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3202, '新增', 'create', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_action_6118cb39 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3203, '修改', 'update', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_menu_action_6118cb39 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3204, '删除', 'delete', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_storage_provid_f9bb387a (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_storage_provid_f9bb387a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3301, '本地存储', 'LOCAL', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_storage_provid_f9bb387a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3302, '阿里云 OSS', 'ALIYUN', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_storage_provid_f9bb387a (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3303, '腾讯云 COS', 'TENCENT', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_sms_provider_d65c9878 (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_sms_provider_d65c9878 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3401, '阿里云短信服务', 'aliyun', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_sms_provider_d65c9878 (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3402, '腾讯云短信服务', 'tencent', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');

CREATE TABLE IF NOT EXISTS sys_di_ai_vendor_f0a49eba (
  id BIGINT PRIMARY KEY,
  sort INTEGER NOT NULL DEFAULT 0,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL UNIQUE,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  status SMALLINT NOT NULL DEFAULT 1,
  tag_color VARCHAR(32),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3501, 'OpenAI / 兼容', 'OPENAI', 'string', 1, 1, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3502, 'Azure OpenAI', 'AZURE_OPENAI', 'string', 1, 2, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3503, 'DeepSeek', 'DEEPSEEK', 'string', 1, 3, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3504, '月之暗面 / Moonshot', 'MOONSHOT', 'string', 1, 4, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3505, '通义千问 (兼容模式)', 'QWEN', 'string', 1, 5, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');
INSERT INTO sys_di_ai_vendor_f0a49eba (id, label, value, value_type, status, sort, tag_color, created_at, updated_at) VALUES (3506, 'Ollama 本地部署', 'OLLAMA', 'string', 1, 6, NULL, TIMESTAMP '2026-01-18 21:21:03', TIMESTAMP '2026-01-18 21:21:03');



-- ----------------------------
-- ----------------------------

-- Demo users/roles
INSERT INTO roles (id, name, description) VALUES
  (1, 'admin', '管理员 - 拥有所有权限')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, account, guid, name, password_hash, status, created_at, updated_at) VALUES
  (
    1,
    'admin',
    'e59c3cd1-3b52-47c7-bf88-fad5b2281827',
    '管理员',
    '$2a$10$BbVSQCIChdR.4gfwiG1OduJiKE/KpUTbhBXd.7Sr.uwi8eggDpYeu',
    1,
    NOW(),
    NOW()
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO user_roles (user_id, role) VALUES (1, 'admin')
ON CONFLICT (user_id, role) DO NOTHING;

INSERT INTO module_registry (module_key, name, version, enabled, install_state, installed_at) VALUES
  ('sms', '短信验证', '1.0.0', 1, 'PENDING', NULL),
  ('email', '邮箱验证', '1.0.0', 1, 'PENDING', NULL);

COMMIT;


